### ISSUE TITLE
[RFE] Needs an About option in the Help Menu.

### ISSUE THREAD

**Issue by trumpy81** [WebTools-NG/WebTools-NG#154]
The title says it all, we need to have an `About` option in the help menu, so that Windows users are more at home ... lol

The About Menu should show the program name of course and it should also show the version of the installed program. There should also be a link to check for updates or to update to the latest version.

EG:

WebTools-NG
Alpha v0.1.3
<Click here to check for updates>

**Comment by ukdtom** [comment]
* The version is in the title bar of the program
* The App name is in the title bar of the program
* Update info will be handled by #103

So still needed ?

**Comment by ukdtom** [comment]
Ping @trumpy81

**Comment by trumpy81** [comment]
Sorry for the delay, but I have not received any notifications for this thread. I am listed as subscribed?

Yes, I do believe this is still required, even though it is mostly unnecessary. Windows folks are used to seeing such a menu option and instinctually go to the Help > About menu when looking for version information etc.

**Comment by ukdtom** [comment]
@CPSO Can you take a look at this?

**Comment by CPSO** [comment]
![webtools about](https://user-images.githubusercontent.com/5735792/95655336-ceabb180-0b06-11eb-888d-7ab62c0b8e67.PNG)

Something like this?

**Comment by ukdtom** [comment]
Think we only need Version Architecture and maybe platform (See wtutils) I would say
