### ISSUE TITLE
[BUG] Quote + comma in summaries prematurely closes CSV fields

### ISSUE THREAD

**Issue by DrKain** [WebTools-NG/WebTools-NG#172]
**Describe the bug**
When a movie summary or tagline contains quotes followed by a comma, the CSV field will be incorrectly closed.
Example: `in search of the crew of spaceship "Bellerophon", a scientific expedition`

**To Reproduce**
1. Find a media item with that fits the example above  
2. Select export level 2 and export  
3. Open the file in any [CSV viewer](https://limonte.github.io/csv-viewer-online/)

**Expected behavior**
Quotes should be escaped

**Screenshots**
Example from another movie with the same issue
![1](https://i.imgur.com/4SPk0yH.png)

**Desktop (please complete the following information):**
 - OS: Windows 7/10

**Comment by ukdtom** [comment]
Confirmed

**Comment by ukdtom** [comment]
What OS are you running this on?

**Comment by ukdtom** [comment]
Next build will contain a fix for this
