### ISSUE TITLE
[BUG] Alpha 0.1.5 CSV & XLSX output not as expected

### ISSUE THREAD

**Issue by trumpy81** [WebTools-NG/WebTools-NG#181]
Using the ExportTools module and selecting TV Episodes and the appropriate library etc., the output is not what is expected.

It seems that some ID numbers are parts of the description and not a number. The description appears to be line wrapping incorrectly.

The majority of the listings appear to be correct with only a few entries not behaving.

I have attached some example files for you to check.

I am hoping you can identify if the issue is with ExportTools or my Plex database or some other cause.

[output.zip](https://github.com/WebTools-NG/WebTools-NG/files/5309129/output.zip)

**Comment by ukdtom** [comment]
Might relate to https://github.com/WebTools-NG/WebTools-NG/issues/179

**Comment by ukdtom** [comment]
Was related ;)
