### ISSUE TITLE
[RFE] Ability for users to empty File Caches

### ISSUE THREAD

**Issue by trumpy81** [WebTools-NG/WebTools-NG#228]
I am wondering if it is possible to create a tool module in WebTools-NG that will remove all entries in these locations (and any other file cache locations):

Mac/Linux
/Library/Application Support/Plex Media Server/Plug-in Support/Caches
/Library/Application Support/Plex Media Server/Plug-in Support/Data
/Library/Application Support/Plex Media Server/Cache/Photo Transcoder

Windows
/Plex Media Server/Plug-in Support/Caches
/Plex Media Server/Plug-in Support/Data
/Plex Media Server/Cache/Photo Transcoder

Is it doable?

**Comment by ukdtom** [comment]
I can't, since this is a desktop app, that might run on another box than the PMS, and as such, have no access to the file system :(
