### ISSUE TITLE
ET - Does not output if the output folder does NOT exist

### ISSUE THREAD

**Issue by trumpy81** [WebTools-NG/WebTools-NG#239]
**Describe the bug**
If the output folder, as defined in ExportTools settings, does NOT exist, then ExportTools will NOT output any files despite going through all of the motions.

**To Reproduce**
1. Setup a path to output the files to, then delete the folder
2. Proceed to configure and use the ExportTools module to output the xlsx and csv files
3. Go to the now non-existent folder

**Expected behavior**
If the output folder does NOT exist, then the folder should be created and the relevant files placed there.

Tested on WIndows 10.
WebTools-NG v0.1.13.5f67924

**Logs**
[WebTools-NG.zip](https://github.com/WebTools-NG/WebTools-NG/files/5969774/WebTools-NG.zip)

**Comment by ukdtom** [comment]
Fixed with above
