### ISSUE TITLE
[RFE] Button or setting to restore WebTools-NG default settings

### ISSUE THREAD

**Issue by trumpy81** [WebTools-NG/WebTools-NG#242]
It may be useful to have a 'Restore To Defaults' type button or setting to allow a user to 'start over' if they wish to.

This would effect Global Settings as well as any Module settings, etc...

It would be effective after restarting WebTools-NG.

**Comment by ukdtom** [comment]
Fixed with above

**Comment by ukdtom** [comment]
We only nuked the settings file, we need everything :(
