### ISSUE TITLE
Genre in ExportTools [RFE]

### ISSUE THREAD

**Issue by tangentsoft** [WebTools-NG/WebTools-NG#307]
**Describe the solution you'd like**
The old ExportTools plugin let you export the Genre of movies at high Levels. I've tried creating a custom level, and the old "Genres" field isn't even listed.

More generally, I want the tool to export *everything*, because the next step is to slurp everything into a SQLite DB for further querying and manipulation. (Side feature request: offer a direct SQLite export option.)

**Describe alternatives you've considered**
I'm going back to the plugin for now.

**Comment by ukdtom** [comment]
That's why this isn't released yet ;)

Still in the process of validating the output fields, as seen here:
https://github.com/WebTools-NG/WebTools-NG/blob/master/docs/modules/ExportTools/Fields.md

Genre will be part of movies in the next release

**Comment by ukdtom** [comment]
And regarding SQLite, then out of scope for now, but why doesn't you simply make a backup from PMS, and the use that directly?

**Comment by ukdtom** [comment]
Fixed in commit #313

**Comment by tangentsoft** [comment]
> why doesn't you simply make a backup from PMS, and the use that directly?

Just to close the loop on this, the answer is that the schema of the SQLite DB created from the CSV emitted by ExportTools (or WebTools-NG) is far simpler than the Plex DB schema. Not only is the SQLite output for the `.schema` command simpler, I have a much better chance of figuring out what to query and how atop a simple flat file than the complicated Plex schema.
