### ISSUE TITLE
[RFE] Mac OS X Install 

### ISSUE THREAD

**Issue by schultz2146** [WebTools-NG/WebTools-NG#308]
From "Installing WebTools-NG"  

There is no clear guidance for Mac users for adding the Plex Token which is required for WebTools-NG to see the server.  

Request you add Mac OS X support with the following:

Run an application inside Terminal.
	1	Locate the application in Finder.
	2	Right-click the application and select "Show Package Contents."
	3	Locate the executable file. ...
	4	Drag that file onto your blank Terminal command line and add X-Plex-Token=(your token)
	5	Leave your Terminal window open while you use the application.

**Comment by ukdtom** [comment]
@trumpy81  Can you take a look at this?

**Comment by trumpy81** [comment]
Apologies for the delay. I was not aware of this issue, no notification about this thread at all and I only just found this thread.

The Wiki has been updated to include instructions for running WebTools-NG on the Mac.
