### ISSUE TITLE
[BUG] Wont let me log in after installing.

### ISSUE THREAD

**Issue by Lee-Robertson** [WebTools-NG/WebTools-NG#309]
On the advice of a member of the PLEX community I have joined github and downloaded WebTools in order to export a file list from my PLEX media server.

I have installed it, then inputted my PLEX username and password. Both checked and both correct. There is no 2F Authentication to deal with as I never enabled it in my PLEX.

I tick the box to 'Remember Username'
I click the blue 'Sign In' button
... and nothing happens. At all!

Any help or advice would be greatly appreciated.

Desktop: 
Edition: Windows 10 Home (OS Build 19041.867)

**Additional context**
This has all come about  due to my Asustor 5304T NAS that carried 4x 16TB Seagate IronWolf Pro drives for some reason wiped the drives overnight. The drives are showing as empty with one unstable drive. The PLEX is still showing all of my files though. I now need to find a way to export my file lists so I can start to rebuild my libraries as the data recovery with drives of this size is almost £4,000. Way beyond my reach and twice what the system even cost me to set up.

**Logs**
Non available as I am unable to log in.

**Comment by ukdtom** [comment]
We auth towards plex.tv, but note we only supports plex.tv auth, not Google etc.

**Comment by ukdtom** [comment]
Ping

**Comment by ukdtom** [comment]
Final ping

**Comment by ukdtom** [comment]
Closed due to lack of response
