### ISSUE TITLE
[BUG] IMDB ID not available for movies

### ISSUE THREAD

**Issue by jalarab** [WebTools-NG/WebTools-NG#339]
**Describe the bug**
When I selected Movies and level All the final file doesn't have the IMDB ID column
When I tried to create a custom level  for movies including the IMDB ID field, it is not in the list

**Desktop (please complete the following information):**
Windows 10, version 0.3.3.76548bc

**Comment by ukdtom** [comment]
Darn, I broke it :(

I'll look into it, and thanks for reporting it

**Comment by ukdtom** [comment]
Problem is kinda complex, and due to old agents vs. new agents, and they store data in different places

**Comment by ukdtom** [comment]
Heh....

It was there, but named `MetaData Language` and `MetaDB Link`

But one thing is that OP was confused, but I was as well....SIGH....

As such, with the next release,  `MetaData Language` and `MetaDB Link` will be gone, and replaced with:

* "IMDB ID (Legacy)"
* "IMDB Language (Legacy)"
* "IMDB Link (Legacy)"
