### ISSUE TITLE
[Support] MAcOS detects Plex Media Servers, but only list libraries on one of them (2 servers installed)

### ISSUE THREAD

**Issue by magefesa** [WebTools-NG/WebTools-NG#346]
**Describe the bug**
I have 2 PMS, 1 on NAS, 1 on Mac Mini
Webtools-ng installed on MacMini, works fine with PMS_NAS, and also connects to PMS_Mac_Mini.

Is able to list users on both PMS, but not able to export on PMS_MAcMini

**To Reproduce**
1. Go to 'ExporTools
2. Click on Reload server -> A red circle appears on library combo, but nothing happens.
3. No error, but combo fills empty

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows 10, OpenSuse Leap 15.2 etc.]

**Additional context**

**Logs**
[2021-04-19 20:03:13.511] [info] Selected server: Frankv2
[2021-04-19 20:03:13.558] [warn] No response recieved

**Comment by ukdtom** [comment]
I need a zip with the full log, in silly mode please

https://github.com/WebTools-NG/WebTools-NG/wiki/Troubleshooting

**Comment by ukdtom** [comment]
Ahhh......

And could be due to missing playlists!

See: https://github.com/WebTools-NG/WebTools-NG/blob/master/README.md

**Comment by magefesa** [comment]
YES !!! Was That !!
I m so sorry !! I ‘ve read the wiki…I can not believe why didn’t see that !

Thanks a lot !

Frank

--

**Comment by ukdtom** [comment]
NP, and a bug I introduced, but since I had playlists on all the servers I tested against, I sadly didn't catch it in time

**Comment by magefesa** [comment]
No patreon or similar to doantions ??

Frank

--

**Comment by magefesa** [comment]
You deserve that !!
I ve donated to Tautulli last 2 years, also donated to a Ghost Theme developer... Free is ok, but when it s a tool used habitually, I think it s necessary to pay for that.

Great work, thanks !

Frank

--

**Comment by ukdtom** [comment]
I wrote WebTools.bundle as well, and if you look at the stats, it has +442.000 downloads for the latest release.

For that, I did as a test allowed donations....

In 3 years, I got about $300,-  so not an optimist here ;-)

**Comment by ukdtom** [comment]
I guess I'm simply a bad sales guy

**Comment by magefesa** [comment]
I m preparing a few videos of top skill tools for PleX, your tools will be there. Would be good to know a patreon or paypal to point.

Frank

--

**Comment by ukdtom** [comment]
Timeframe?

**Comment by magefesa** [comment]
No problem of time ! At least 1 month !! All depends of my free time... with 2 kids is difficult to plan anything... I m writing scripts right know...

Frank

--

**Comment by ukdtom** [comment]
Footer of the Wiki now has a donate button

**Comment by magefesa** [comment]
One donation at least... Won t pay 1 hour of your time, but ....

Frank

--

**Comment by ukdtom** [comment]
Do share a link when you release your video(s)

**Comment by ukdtom** [comment]
Hopefully fixed with the version just released
