### ISSUE TITLE
[BUG] No Media Library is showing

### ISSUE THREAD

**Issue by ink79** [WebTools-NG/WebTools-NG#347]
**Describe the bug**

I'm trying to export my audio library, when I select Select Export Type Audio Track my library does not show up in Select Media Libary & the icon keeps spinning.

**Desktop (please complete the following information):**
 - ubuntu 18.04

**Additional context**
only audio is on the plex server & size of the plex db is 2.4GB

**Logs**

[info] Returning valid address as: 
[info] fetchSections called

**Comment by ukdtom** [comment]
https://github.com/WebTools-NG/WebTools-NG/wiki/Known-Issues#-exporttools

**Comment by ink79** [comment]
I was using only CSV but still, nothing, hope you will fix the huge library issue in the future

**Comment by ukdtom** [comment]
In the wiki I linked towards, it says:

If you don't have at least one playlist, ET Module will not show the list of libraries
WorkAround: Create a dummy playlist with at least one item of the type you want to export
Fix slated for next release

**Comment by ukdtom** [comment]
Issue hopefully fixed with the new version just released
