### ISSUE TITLE
if possible allow lan only connections

### ISSUE THREAD

**Issue by ghvader** [WebTools-NG/WebTools-NG#366]
**Is your feature request related to a problem? Please describe.**
none of my libraries or settings would load, after turning on debug logging, I saw that you are routing through plex.direct
but I don't have remote access or any open ports from the internet to my server. so the app is unable to connect

**Describe the solution you'd like**
ability to connect on LAN only without having the server opened to the outside world

**Describe alternatives you've considered**
none

**Additional context**
n/a

**Comment by ukdtom** [comment]
Since we do auth against plex.tv, the server must be online

**Comment by ukdtom** [comment]
Hmmm.....You actually might have a point here, since I also should be able to prefer direct IP access, as long as the server is published on plex.tv

Will look into this

**Comment by ukdtom** [comment]
Note to self:
https://plex.tv/api/v2/resources?X-Plex-Client-Identifier=1234abc&includeHttps=1

**Comment by ukdtom** [comment]
@ghvader 

If your PMS is not connected to the internet, then how do you authenticate towards it?

**Comment by ukdtom** [comment]
Ping...

**Comment by ghvader** [comment]
> Ping...

sorry didnt see the last post. It is connected to the internet, I just don't have open port for incoming traffic to it. the server can get OUT, and when you make an outbound connection the firewall will allow traffic back in to the device that made it. so that is how it auth's. however this app is a windows app it's ran on a different machine (i'm running plex on a freebsd machine) so this this app auth's to plex servers, but when it trys to connect to my plex server it's going out and trying to come back in to a different server, which it can't do.. so that is why a direct to IP or local host name is requested. so it doesn't go out and try to come back in. If i were running plex on this machine, it would probably work. but not the case here. 
I removed some info for privacy, but you can see once this app auth's it  then trys to connect into my server, but my server didn't make the request so firewall won't allow that traffic.
```
[2021-05-07 21:44:28.957] [info] Selected server: <removed>
[2021-05-07 21:44:28.957] [verbose] Checking address for server: <removed>
[2021-05-07 21:44:28.958] [verbose] Checking: https://192-168-2-<removed>.<removed>.plex.direct:32400
[2021-05-07 21:44:29.553] [warn] No response recieved
[2021-05-07 21:44:29.553] [verbose] Checking: https://192-168-2-<removed>.<removed>.plex.direct:32400
[2021-05-07 21:44:29.666] [info] fetching servers
[2021-05-07 21:44:29.831] [debug] Response from fetchPlexServers recieved
```

**Comment by ukdtom** [comment]
Okay, I'll see what I can do

**Comment by ukdtom** [comment]
Issue most likely due to DNS Rebinding.
Fixed checked in, and slated for next release

**Comment by ukdtom** [comment]
Please let me know if it works now for you

**Comment by ghvader** [comment]
> Please let me know if it works now for you

Yes it does indeed work now.  nice job.. thanks!
