### ISSUE TITLE
[RFE] Remove setting from ExportTools Settings

### ISSUE THREAD

**Issue by trumpy81** [WebTools-NG/WebTools-NG#373]
On the ExportTools settings page, we find the following setting:

---

 _Timeout when requesting info from PMS in sec (Global setting)_

---

This setting does not belong on the ExportTools Settings page and already exists on the Global Settings page.

Also, consider removing theses settings, as they cannot be selected at present:

_Autosize column (xlsx only)
Autosize row (xlsx only)_

**Comment by ukdtom** [comment]
Will be part of the next release

**Comment by ukdtom** [comment]
When released, we need to update Wiki and pics for that

**Comment by ukdtom** [comment]
And released ;)
