### ISSUE TITLE
[RFE] Change the Poster/Art Height * Width settings.

### ISSUE THREAD

**Issue by trumpy81** [WebTools-NG/WebTools-NG#374]
At present, the Poster and Art dimensions settings are given as **Height** x **Width**.

However, these dimensions are normally given as **Width** x **Height**. EG: 1920w x 1080h (FHD)

The current settings require entering the dimensions like so: 1080h x 1920w

This can be a little confusing for some users.

This request is to swap those two values in the settings to become **Width** x **Height**.

Also, a reminder, that output of Posters and Artwork, fail.

**Comment by ukdtom** [comment]
Posters/Arts export broke due to #366

Need to figure out new way to download those, SNIFF

**Comment by ukdtom** [comment]
This will be part of the next release
