### ISSUE TITLE
install on Ubuntu fails

### ISSUE THREAD

**Issue by getuslocal** [WebTools-NG/WebTools-NG#393]
**Describe the bug**
I am unable to install on Ubuntu. 

**To Reproduce**
I downloaded the AppImage and clicked on it to install as per the instructions but I get an error Invalid URL: No ':' in the uri

**Expected behavior**
I expected install to start

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS

**Comment by ukdtom** [comment]
Sadly, we can't reproduce this, and tested on the same version/distro as you have

Anything in any logs about this?
And you did make it executable before clicking on it?

**Comment by ukdtom** [comment]
Closed due to lack of response
