### ISSUE TITLE
[RFE] How to Install on Docker 

### ISSUE THREAD

**Issue by zinkmovies** [WebTools-NG/WebTools-NG#397]
**Here is my docker-compose.yaml file**

version: "3.4"
services:
  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/downloads:/downloads # downloads folder
      - ${ROOT}/config/deluge:/config # config files
    ports:
      - "8112:8112"

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
      - ${ROOT}/config/jackett:/config # config files
    ports:
      - 9117:9117
      
  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/downloads:/downloads # download folder
      - ${ROOT}/config/nzbget:/config # config files
    ports:
      - 6789:6789

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/radarr:/config # config files
      - ${ROOT}/complete/movies:/movies # movies folder
      - ${ROOT}/downloads:/downloads # download folder
    ports:
      - 7878:7878

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/sonarr:/config # config files
      - ${ROOT}/complete/tv:/tv # tv shows folder
      - ${ROOT}/downloads:/downloads # download folder
    ports:
      - 8989:8989
      
  plex-server:
    container_name: plex-server
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ} # timezone, defined in .env
      - PLEX_CLAIM=XXXXXXXXXXXXXXXXXXXXXX
    volumes:
      - ${ROOT}/config/plex/db:/config # plex database
      - ${ROOT}/config/plex/transcode:/transcode # temp transcoded files
      - ${ROOT}/complete:/data # media library
    ports:
      - "32400:32400"
      - "1901:1901/udp"
      - "3005:3005"
      - "5354:5354/udp"
      - "8324:8324"
      - "32410:32410/udp"
      - "32402:32402/udp"
      - "32403:32403/udp"
      - "32404:32404/udp"
      - "32469:32469"

  bazarr:
    container_name: bazarr
    image: ghcr.io/linuxserver/bazarr
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - UMASK_SET=022 #optional
    volumes:
      - ${ROOT}/config/bazarr:/config # config files
      - ${ROOT}/complete/movies:/movies # movies folder
      - ${ROOT}/complete/tv:/tv # tv shows folder
    ports:
      - 6767:6767
  
  overseerr:
    container_name: overseerr
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=${TZ}
    image: ghcr.io/hotio/overseerr
    ports:
      - 5055:5055
    restart: unless-stopped
    volumes:
      - ${ROOT}/overseerr:/config
      - ${ROOT}/storage
    labels:
      - "traefik.enable=true"
  ## HTTP Routers
      - "traefik.http.routers.overseerr-rtr.entrypoints=https"
      - "traefik.http.routers.overseerr-rtr.rule=Host(`plex.example.com`)"
      - "traefik.http.routers.overseerr-rtr.tls=true"
  ## HTTP Services
      - "traefik.http.routers.overseerr-rtr.service=overseerr-svc"
      - "traefik.http.services.overseerr-svc.loadbalancer.server.port=5055"
    
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - ${ROOT}/config/qbittorrent:/config
      - ${ROOT}/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped

**[ Above Are My docker.compose.yaml Configuration ]
**[ There Is No Information How to Install WebTool-NG on Docker ]****

**Comment by ukdtom** [comment]
Not a docker person myself, and also note that WebTools-NG req. a GUI, which might not be avail on a docker host, so will close this.

If you however come up with a solution, please post it, and I'll make a ref to it up here

**Comment by andrew-kennedy** [comment]
Wait, isn't the whole idea of web tools that it's all javascript and can run in the browser? Why can't it be run in a docker container with a web server to serve it up, and then point it at plex?

**Comment by ukdtom** [comment]
Might be able to, but out of scope for now.
I simply haven't got the time to figure that out, since already have enough on the roadmap

Also consider this not vital, since I guess about 99 % of all users has a workstation with a desktop

When said, I always welcome a PR with the solution
