### ISSUE TITLE
[BUG] Does the AppImage work on arm systems?

### ISSUE THREAD

**Issue by ufilme** [WebTools-NG/WebTools-NG#401]
**Describe the bug**

`-bash: ./WebTools-NG-0.3.12.898c1ee.AppImage: cannot execute binary file: Exec format error`

**Desktop (please complete the following information):**
 - OS: 20.04.1-Ubuntu aarch64

**Comment by ukdtom** [comment]
Heh, never tried, but sadly guess not

And sadly haven't got an arm device, and time-wise also sadly drowning in real work, so no time for a while to test this with VMWare :(

For now, please try another workstation, but keeping this open for future test

**Comment by trumpy81** [comment]
Before you can use the .appimage package you must make the package executable.

This page may help you get the package installed in uBuntu.
https://www.linuxandubuntu.com/home/how-to-open-appimage-in-linux

**Comment by ufilme** [comment]
> Before you can use the .appimage package you must make the package executable.
> 
> 
> 
> This page may help you get the package installed in uBuntu.
> 
> https://www.linuxandubuntu.com/home/how-to-open-appimage-in-linux

Already did

**Comment by trumpy81** [comment]
I just tried the .apimage package on ubuntu 20.04.2 LTS and had no issues opening the package from the GUI at all.

![image](https://user-images.githubusercontent.com/12381786/130348375-03c437af-74ba-4556-8de1-f8fd2b322871.png)

**Comment by ukdtom** [comment]
Closing due to lack of response
