### ISSUE TITLE
[BUG] Exporting issues with delimiters under windows

### ISSUE THREAD

**Issue by vk2tds** [WebTools-NG/WebTools-NG#404]
I created a custom Level under the windows software for exporting movies and TV. Since I was only interested in Filename, I selected :
* Part File
* Part File Combined
* Part File Path

Part File left off the leading " and Part File Path left off the trailing ". This makes parsing the fields correctly more difficult.

```
The.Big.Bang.Theory S09E08.mp4"|"V:\Torrents\The Big Bang Theory\The.Big.Bang.Theory S09E08.mp4"|"V:\Torrents\The Big Bang Theory
The.Big.Bang.Theory S09E09.mp4"|"V:\Torrents\The Big Bang Theory\The.Big.Bang.Theory S09E09.mp4"|"V:\Torrents\The Big Bang Theory
The.Big.Bang.Theory S09E10.mp4"|"V:\Torrents\The Big Bang Theory\The.Big.Bang.Theory S09E10.mp4"|"V:\Torrents\The Big Bang Theory

```

**Comment by ukdtom** [comment]
Fixed with #420
