### ISSUE TITLE
[BUG] Unable to sign in

### ISSUE THREAD

**Issue by damianjmcgrath** [WebTools-NG/WebTools-NG#405]
**Describe the bug**
I downloaded WebTools-NG-0.3.12.898c1ee and ran it. It opened the main screen and prompted me for a username and password. I entered this and clicked the blue Sign In button. Nothing happened at all.

**To Reproduce**
1. Open app.
2. Enter details
3. Click Sign In

**Expected behavior**
I expected it to sign me in and show me another screen.

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/90637271/133118037-73040ca1-e25b-4210-8883-f7cc8a40ad19.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 64 bit

**Additional context**
- I am running Plex Server on a Synology DSM 7.0 NAS. I can log into plex.tv using the credentials fine, and see all of my content. My laptop and Synology NAS are on the same subnet, connected to the same router. I have reset my laptop, router and Synology NAS box a few times, but still, the issue continues. The logs suggest my user credentails are incorrect and then mentions about my IP being unable to connect. I have tried disabling the Windows Firewall, and then allowing WebTools-NG through the firewall but both gave the same result.
- My Plex does not have 2FA enabled.
- I have tried using Username and Email, but both give the same result.
- I have tried using earlier versions of WebTools-NG but they all do the same thing, i.e., unable to sign in.

**Logs**
Please provide WebTools-NG logs in a zip
[WebTools-NG.zip](https://github.com/WebTools-NG/WebTools-NG/files/7155724/WebTools-NG.zip)

**Comment by ukdtom** [comment]
All I see in the logs are:

`[2021-09-13 16:49:26.653] [error] loginToPlex data: {"errors":[{"code":1031,"message":"User could not be authenticated. This IP appears to be having trouble signing in to an account (detected repeated failures)","status":401}]}`

And above is from plex.tv itself....

So try this:

From a browser, open an incognito windows, and access plex.tv and sign in
Does the credentials work there?

Also note, that we only support native plex auth, and not FB nor Google auth

**Comment by ukdtom** [comment]
Ping

**Comment by ukdtom** [comment]
Closing due to lack of response
