### ISSUE TITLE
[BUG] Cannot install Synology SPK

### ISSUE THREAD

**Issue by damianjmcgrath** [WebTools-NG/WebTools-NG#406]
**Describe the bug**
I downloaded the Synology spk from https://github.com/ukdtom/WTInstaller/releases/tag/1.2 and when I tried to install it through the Synology DSM 7 web interface, it said invalid file format.

**To Reproduce**
1. Download Synology SPK from https://github.com/ukdtom/WTInstaller/releases/tag/1.2
2. Open Synology NAS DSM
3. Go to package centre
4. Click Manual install
5. choose SPK file
6. Error occurs

**Expected behavior**
The SPK would have installed as a package.

**Screenshots**
![Screenshot_2](https://user-images.githubusercontent.com/90637271/133120232-bf3206f4-6bbb-4f28-a140-b42c62f10c6c.png)

**Desktop (please complete the following information):**
 - OS: Synology DSM 7.0

**Additional context**
File is called Synology_Inst_WebTools_1.4.spk

**Logs**
Please provide WebTools-NG logs in a zip

**Comment by trumpy81** [comment]
WebTools and WebTools-NG are two different things. The WebTools plugin is no longer developed.

Plugins are no longer supported by Plex, they will be removed completely from Plex in the near future.

The WebTools plugin installer was written for DSM 6, so it will fail when attempting to install it in DSM 7.
