### ISSUE TITLE
[BUG] Poster export stops when no poster attached to a Plex movie

### ISSUE THREAD

**Issue by Philippe-MTL** [WebTools-NG/WebTools-NG#408]
Not really a bug, rather a hint that could be given...

Had to extract posters from an OSX Plex libray of 1000+ 'home' movies (mostly operas that do not exist on IMdB) so I could attach them to a new Plex library on a QNAP server.

After 249 extracts, Export Tool would hang, leaving the expected **csv** file as a **tmp** file.  Log file would not say much (even in **debug** or **verbose** mode).

Having **Default "Sort Title" to "Title", if empty** set help me to find out where the process stopped.

All I had to do is to go down the list of movies in plex and reattach the Poster when none was selected.

Hope that will help someone.

A big thank you to Tommy and team for the great tool !

- Philippe

**Comment by ukdtom** [comment]
Poster/Art will now be skipped, and logged properly in the log

**Comment by ukdtom** [comment]
Even better....
We now produce a file named like: 
`__ERROR__22860_The SpongeBob SquarePants Movie_75x75.txt`

With contents like:
`etHelper (forceDownload-downloadError) downloading pic for "The SpongeBob SquarePants Movie" caused an exception as: Error: Request failed with status code 500`

**Comment by Philippe-MTL** [comment]
Excellent !

Philippe

Le ven. 3 déc. 2021, 06 h 10, Tommy Mikkelsen ***@***.***> a
écrit :
