### ISSUE TITLE
[BUG] Part has Thumbnail column title

### ISSUE THREAD

**Issue by Philippe-MTL** [WebTools-NG/WebTools-NG#409]
When asking for full export, the **xlsx** file has one extra column name on **column BU** : **Part has Thumbnail**

![Export](https://user-images.githubusercontent.com/60315564/136775837-94386de1-7ea9-43c2-99c3-bf3fb190270d.jpg)

Not a big deal, though ;)

- Philippe

**Comment by Philippe-MTL** [comment]
I think so. Here is the setting I used :

![ExportAll](https://user-images.githubusercontent.com/60315564/137157079-1b15291c-2fbb-4479-8edf-05dfdbfd847c.jpg)

**Comment by trumpy81** [comment]
**Part has Thumbnail** is a standard level that can be exported.
