### ISSUE TITLE
[RFE] Allow setting the LogNumFiles from Settings

### ISSUE THREAD

**Issue by shark2k** [WebTools-NG/WebTools-NG#429]
**Is your feature request related to a problem? Please describe.**
Not really a problem, just making it easier to set/change another hidden/advanced settings

**Describe the solution you'd like**
It would be awesome if the LogNumFiles setting in the hidden/advanced settings was able to be set from the Settings section under the Plex Media Server section within this tool.

**Describe alternatives you've considered**
Updating that setting manually via the appropriate area depending on the OS you are on.

Thanks,
Shark2k

**Comment by ukdtom** [comment]
Interesting.....

When I populate the list of settings to show, I ask PMS for them.

Req. setting is really, as in really hidden

**Comment by shark2k** [comment]
I figured either I was missing something or maybe it was overlooked as I didn't see any reason for it not to be there.
Good to know it wasn't me and that it was because it just really, **_really_** hidden.

Not quite sure of the flow so either thanks for adding it as something to do or for getting it added in so it works!

-Shark2k

**Comment by ukdtom** [comment]
Added a GHI to Plex for this
