### ISSUE TITLE
[BUG] Thumb Download failure causes export to fail

### ISSUE THREAD

**Issue by dbirchbauer** [WebTools-NG/WebTools-NG#430]
When doing a custom export including posters if the export fails to download a thumb the process aborts, instead of just skipping that poster.

Status: Idle
Info: Fetching X items in chunks of 30
Chunks: Processing chunk 20 of Y
Items: Processing item 611 of X
Start time: 11:56:1
Running time: 0:11:23

Fields:
Key
IMDB ID
Part File
Title
Year
Export Posters

**Desktop (please complete the following information):**
 - OS: Windows 10
**Logs**
[2021-12-23 12:07:26.714] [error] Failed to download https://\<IPADDRESS>:13715/photo/:/transcode?width=768&height=1024&minSize=1&url=/library/metadata/138674/thumb/1631411220

**Comment by ukdtom** [comment]
Will be fixed in next release

See: #408
