### ISSUE TITLE
[BUG] Exports - Some TV shows being "merged" into one line of the export

### ISSUE THREAD

**Issue by pekempy** [WebTools-NG/WebTools-NG#439]
**Describe the bug**
An example below with: Series title;Title;Season;Episode;Poster url;Part File Combined as the CSV export custom level.
As you can see, "Doctor Who 2005 Reboot" is also picking up the files from "Doctor Who" (the classic series), and saying that both files (_ separated) are for the same show/episode when this is not the case.

`"Doctor Who 2005 Reboot";"Bad Wolf (1)";"1";"12";"/library/metadata/129040/thumb/1643189682";"F:\TV Shows\Doctor Who\Season 1\Doctor Who - S01E12 - The Edge of Destruction (1) SDTV.avi_E:\TV Shows\Doctor Who (2005)\Season 1\Doctor Who (2005) - S01E12 - Bad Wolf (1) SDTV.avi"`

**To Reproduce**
1. Go to **Custom Levels**
2. Create a TV Episodes level with: Series title;Title;Season;Episode;Poster url;Part File Combined
3. Create an export with two similarly named shows (in this case the file names are above)

**Expected behavior**
There should be two separate CSV entries as follows:
`"Doctor Who";"The Edge of Destruction (1)";"1";"12";"/library/metadata/129040/thumb/{some other ID}";"F:\TV Shows\Doctor Who\Season 1\Doctor Who - S01E12 - The Edge of Destruction (1) SDTV.avi"`

`"Doctor Who 2005 Reboot";"Bad Wolf (1)";"1";"12";"/library/metadata/129040/thumb/1643189682";"E:\TV Shows\Doctor Who (2005)\Season 1\Doctor Who (2005) - S01E12 - Bad Wolf (1) SDTV.avi"`

**Desktop (please complete the following information):**
 - Windows 10, WebTools-NG v0.3.13.e0b50d0
 
**Logs**
[logs.zip](https://github.com/WebTools-NG/WebTools-NG/files/7940815/logs.zip)

I've created a custom C# program to grab the posters and export to the media file location but the above is causing issues where some episodes are getting the wrong poster exported

**Comment by ukdtom** [comment]
If you see that episode in the Plex WebClient, and select to see the XML, what does that show?

Ref: https://support.plex.tv/articles/201998867-investigate-media-information-and-formats/

**Comment by pekempy** [comment]
> If you see that episode in the Plex WebClient, and select to see the XML, what does that show?
> 
> Ref: https://support.plex.tv/articles/201998867-investigate-media-information-and-formats/

Ah, bloody Plex seems to have merged them even though they were split fine before. I'll try plex dancing it around and see if I can get them un-merged. The seasons have disappeared from Classic entry too

**Comment by ukdtom** [comment]
So a PMS matching issue

Suggest you look here: 
https://support.plex.tv/articles/naming-and-organizing-your-tv-show-files/

And add both year and tndb-id to the show folder, if not already present
