### ISSUE TITLE
[BUG] installing on Synology DS720+

### ISSUE THREAD

**Issue by jebmdk** [WebTools-NG/WebTools-NG#442]
./WebTools-NG-0.3.13.e0b50d0.AppImage
/tmp/.mount_WebToo0ZwrhY/webtools-ng: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory

Synology DS720+ DSM 6.2.4-25556 Update 3

uname -r 
Linux XXX 4.4.59+ #25556 SMP PREEMPT Sat Aug 28 02:17:25 CST 2021 x86_64 GNU/Linux synology_geminilake_720+

find / -name "libatk*"
Zero hits

**Comment by ukdtom** [comment]
It's a client/server program, that should be installed on your workstation, not on your NAS
