### ISSUE TITLE
[BUG] Track artist isn't included in audio playlist export

### ISSUE THREAD

**Issue by correctomundo79** [WebTools-NG/WebTools-NG#447]
**Describe the bug**
When exporting a audio playlist, the track artist isn't included.

**To Reproduce**
1. Go to 'Exporttools'
2. Select export type 'Playlist', sub type 'Audio'
3. Select the applicable playlist from 'select media library'
4. Select all levels
5. Select 'export media'
6. A file is successfully exported, but the track artist isn't included

**Expected behavior**
To include the track artist in the export.

**Screenshots**
N/A
**Desktop (please complete the following information):**
 - OS: Windows 10. Webtools v0.3.13

**Additional context**
N/A

**Logs**
Not required for this issue I guess. If you want it, let me know and I will share.

**Comment by ukdtom** [comment]
Sadly, that is not exposed by PMS when viewing a Track in a playlist

As such why that's not supported, sadly
