### ISSUE TITLE
Wiki updates

### ISSUE THREAD

**Issue by ukdtom** [WebTools-NG/WebTools-NG#452]
Hi @trumpy81 

V0.3.14 contains a new thing for movies, named `suggested naming`

![image](https://user-images.githubusercontent.com/4699449/159794647-8e9affcb-1d76-446c-bc4e-3407e1d40727.png)

Basically it'll export a list of movies and suggest a better naming, following the new naming std. with imdb hints etc.

There's also changes to the settings

![image](https://user-images.githubusercontent.com/4699449/159794962-27a8405b-b24e-4b68-a354-b59e1c089921.png)

So a Wiki update would be great ;)

**Comment by trumpy81** [comment]
I had already added the changes to settings, but I did miss the change to the Export Level menu. That has been corrected now. :)

**Comment by ukdtom** [comment]
You're the best, Thanks ;)
