### ISSUE TITLE
Unable to open settings cog for this Plugin

### ISSUE THREAD

**Issue by thorrrr** [WebTools-NG/WebTools-NG#458]
HI Guys
I have always been able to open the settings gear cog but it no longer works.
I have tried on 3 different PC's several browsers Virus & Firewall turned off it just spins.
But my other plugins open fine!

**To Reproduce**
Just try to open the settings via the cog

**Expected behavior**
See the settings popup box

**Screenshots**

**Desktop (please complete the following information):**
Unraid Server 6.9.2
Plex Version 4.76.1

**Additional context**
The only thing that could have effected it i added a new port with a comma to try to get Plex to see a new DVR i have been struggling to get Plex to see. It is on my network and i can even curl its ip address of the dvr and it is seen but Plex is not parsing it across. So i didn’t know if your plugin was blocking or need ports adding :(

**Logs**
Please provide WebTools-NG logs in a zip

![image](https://user-images.githubusercontent.com/8170673/161930684-8f44203d-3888-4625-a369-146ef3a55b16.png)

[com.plexapp.plugins.WebTools.log](https://github.com/WebTools-NG/WebTools-NG/files/8425151/com.plexapp.plugins.WebTools.log)

**Comment by ukdtom** [comment]
Above is [WebTools.bundle](https://github.com/ukdtom/WebTools.bundle), not WebTools-NG

When said, it looks like you messed with the ports, since this is in your log:

```
CRITICAL (webSrv:475) - Problem starting Tornado: invalid literal for int() with base 10: '33400,8080' (most recent call last):
  File "/app/config/Plex Media Server/Plug-ins/WebTools.bundle/Contents/Code/webSrv.py", line 468, in start_tornado
    port = int(Prefs['WEB_Port_http'])
```

Go here, and do a manual reset:
https://github.com/ukdtom/WebTools.bundle/wiki/Reset

And closing, since not related to WebTools-NG
