### ISSUE TITLE
Wiki updates needed

### ISSUE THREAD

**Issue by ukdtom** [WebTools-NG/WebTools-NG#465]
In V0.3.15 we released a new module under PMS, that allows us to kickstart a butler thread

Useful, if you like change the backup path, then you don't have to wait up to 3 days to check if it works, but can kickstart it

So we need a wiki update Andy ;)

**Comment by trumpy81** [comment]
I need clarification on the following:

`Useful, if you like change the backup path, then you don't have to wait up to 3 days to check if it works, but can kickstart it`

What do you mean by backup path and for what exactly?

The wiki has been updated (may need more updates?)
