### ISSUE TITLE
[BUG] Non-Localized Time

### ISSUE THREAD

**Issue by SturmB** [WebTools-NG/WebTools-NG#467]
**Describe the bug**
The month number is off by 1 and the time is UTC.

**To Reproduce**
Export anything involving a date/time, such as the `Added` field.

**Expected behavior**
For the month number, I would expect the month number to be correct (1 = January, 2 = February, etc.).
For the time, I would expect it to be auto-adjusted to the local time zone and possibly even corrected for Daylight Savings. Or, at least I would expect an option in Settings to choose between UTC and Local time.

**Screenshots**
![image](https://user-images.githubusercontent.com/6216224/164986396-7e60f867-3b47-4229-847a-86275bcba157.png)

**Desktop (please complete the following information):**
 - OS: Windows 11, latest build as of this writing.

**Additional context**
In the screenshot above, note that "An American Tail" was added to my library on "2022-00-27 11:32:25". This is obviously incorrect. It was actually added on "2022-01-27 06:32:25" in my time zone.

The month number is clearly using a zero-based index, so it should be incremented by one before export.

As for adjusting for the local time zone, I don't know what you'd need to do to make that happen. I just know that I can use a SQL function `strftime()` and add `'localtime'` as the third argument to that function in order to automatically convert it. It will even take care of rolling back the day when it crosses midnight and even the month if it happens to fall on the last day of the month, too.

**Logs**
I do not know how to provide the logs from WebTools-NG, as I see no option for it in menus, nor do I know where it stores its logs. I doubt they are needed for this issue, anyway.

**Comment by ukdtom** [comment]
In the latest build, Plex changed the database format for some time/date fields.
So this would cause the time to be wrong now :(

Regarding time zone, this has never been implemented, so currently, we report what PMS gives us, and have not yet considered to adjust to local time/format, but a good idea

**Comment by SturmB** [comment]
I must amend my findings regarding the time zone. From what I've been able to determine, the time stored in the database _is actually local time_, not UTC time.

Therefore, if you did want to pursue adding an option to output the time in UTC, you'd probably need to get the time zone either from the user (as another field in the options) or from the Plex database (if it's even stored there; I don't know). I only know that it's possible with a query by using the `'utc'` modifier to `strftime()`.

(It turns out that both the `'localtime'` and `'utc'` modifiers _assume_ that the time they are adjusting is of the opposite type. I was unaware of that and just assumed all times in the Plex db were UTC.)

**Comment by ukdtom** [comment]
I was talking about the format, like 12/24 hours clock etc. ;)

**Comment by trumpy81** [comment]
Regarding logs (not needed at this time), you will find the log directory by clicking on the `Open Log Directory` option under the File menu.

See the Wiki for more details: https://github.com/WebTools-NG/WebTools-NG/wiki/File-Menu

**Comment by ukdtom** [comment]
Hopefully, we now have local date/time with V0.3.17

If not, please reopen
