### ISSUE TITLE
[RFE] Add "Last Viewed at" as an available field for TV Show Episode exporting

### ISSUE THREAD

**Issue by SturmB** [WebTools-NG/WebTools-NG#468]
**Is your feature request related to a problem? Please describe.**
When I want to export the list of TV Shows I've watched and upload the date/time when I watched it last to Trakt.tv, I cannot.

**Describe the solution you'd like**
I would like the "Last Watched at" field to be available for TV Show Episodes, just as it is for Movies.

**Describe alternatives you've considered**
The only other solution I have is to export a raw SQL query to a CSV file. It should work fine, but I'd rather use WebTools-NG instead.

**Additional context**
I can think of no other information that would help clarify the request. Please let me know if there's more info I can provide.

**Comment by ukdtom** [comment]
Sadly, when you view an XML for a Season, that info is not avail :(

Below you see an XML from a Season, and below info is more or less the only thing I can extract, since using the web api as the webclient also use

```
<MediaContainer size="1" allowSync="1" identifier="com.plexapp.plugins.library" librarySectionID="2" librarySectionTitle="TV Shows" librarySectionUUID="94102838-a992-411c-b237-cedaf41e26f0" mediaTagPrefix="/system/bundle/media/flags/" mediaTagVersion="1645197512">
<Directory ratingKey="31814" key="/library/metadata/31814/children" parentRatingKey="5638" guid="plex://season/602e6817fdd281002cdf6857" parentGuid="plex://show/5d9c086d705e7a001e6dc723" parentStudio="Warner Bros. Television" type="season" title="Season 6" titleSort="Season 6" parentKey="/library/metadata/5638" librarySectionTitle="TV Shows" librarySectionID="2" librarySectionKey="/library/sections/2" parentTitle="The 100" summary="" index="6" parentIndex="1" year="2019" thumb="/library/metadata/31814/thumb/1635843813" art="/library/metadata/5638/art/1640390073" parentThumb="/library/metadata/5638/thumb/1640390073" parentTheme="/library/metadata/5638/theme/1640390073" leafCount="13" viewedLeafCount="0" addedAt="1556829038" updatedAt="1635843813">
<Guid id="tvdb://774388"/>
<Extras size="0"> </Extras>
<Related> </Related>
</Directory>
</MediaContainer>
```

**Comment by SturmB** [comment]
> Sadly, when you view an XML for a Season, that info is not avail :(

Really? That's quite a shame because I'm able to get the `viewed_at` info from the `metadata_item_views` with a raw SQL query (`library_section_id=2` is for TV Shows and `account_id=1` is my account):

```sql
SELECT miv.viewed_at, mi.added_at, miv.title, mi.year, miv.parent_title, miv.grandparent_title
FROM metadata_item_views miv
JOIN metadata_items mi ON mi.guid = miv.guid
miv.account_id = 1 AND miv.library_section_id = 2;
```

I know you are limited to using the Plex API rather than using raw SQL queries, but I would have figured that it would let you get the viewed dates for episodes. Not seasons nor shows, but the individual episodes themselves.

**Comment by ukdtom** [comment]
Since WebTools-NG is a C/S based util, I can't access the database directly, only via PMS Rest API

**Comment by ukdtom** [comment]
Thanks to the gods, that @trumpy81 is watching over me here and spot where I make mistakes ;)

For some stupid reason, I read your req. as you wanted this on a show level, but you want is for episodes, which is possible!

I'll see if I can get this into the next release

**Comment by ukdtom** [comment]
We must remember to update the [Wiki ](https://github.com/WebTools-NG/WebTools-NG/wiki/Fields )as well when done

**Comment by ukdtom** [comment]
Done for episodes, but bad for shows
We need to add field "Show Title" for shows as well
