### ISSUE TITLE
[BUG] Default ExportTools Levels do NOT produce any output

### ISSUE THREAD

**Issue by trumpy81** [WebTools-NG/WebTools-NG#469]
**Describe the bug**
WebTools-NG v0.3.15.bb900f1

Export Movies using ExportTools default Export Level 1 or Level 2, results in no actual output.
Using the Level All or a Custom Level, does work though.

**To Reproduce**
1. select Server (ROGStrix in this case, also tried DiskStation and PlexStation servers)
2. select Export Type = Movie
3. select Sub type = Movies
4. select Library = Any Movie type library (Documentaries in this case)
5. select Export Level = Level 1 or Level 2

**Expected behavior**
After making the above selections, the .csv file should be output. 

**Desktop (please complete the following information):**
Windows 11 Pro, Synology DSM6 and DSM7.

**Additional context**
I did notice that after outputting the .csv file using the Level All or a custom level, two .tmp files are left behind. Both files are 1 byte in size and contain the column headers, Key, Title, Sort Title etc...

EG:
ROGStrix_Documentaries_Movie_Movies_Level 1_Item 0-236_2022.04.27_7.24.50.csv.tmp
ROGStrix_Movies 4K_Movie_Movies__Item 0-36_2022.04.27_7.19.19.csv.tmp

**Logs**
[WebTools-NG.zip](https://github.com/WebTools-NG/WebTools-NG/files/8567035/WebTools-NG.zip)

**Comment by ukdtom** [comment]
Hi Andy

Could you switch log level to "Silly", restart WT, and then reproduce, and upload a new set of logs?

**Comment by ukdtom** [comment]
And ignore my req....

Was able to duplicate

**Comment by ukdtom** [comment]
@trumpy81 

Could you please reach out to me in a DM, either on the forums, or in Slack
I need a way to contact you privately

**Comment by trumpy81** [comment]
You can email me at trumpy81 @ optusnet.com.au if you wish to.

**Comment by ukdtom** [comment]
Check inbound mail ;)

**Comment by trumpy81** [comment]
Check your inbox and thanks for saving me from scrambling the email ... lol
