### ISSUE TITLE
[BUG] No Media Library Under ExportTools

### ISSUE THREAD

**Issue by Droppisalt** [WebTools-NG/WebTools-NG#485]
**Describe the bug**
Unable to select Media Library under ExportTools.

**To Reproduce**
Go to ExportTools
Select Export Type & Sub Type
Click on drop-down for Media Library
Drop-down is empty

**Expected behavior**
I should see my libraries ('Movies' and 'Anime Movies')

**Screenshots**
![image](https://user-images.githubusercontent.com/67336980/167870671-4d219e64-69a5-444e-81a1-04125a0f45a5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Server is on Docker on another PC

**Logs**

**Comment by trumpy81** [comment]
I am not seeing this issue at all, but then I do not run PMS in a Docker at all.

I suspect that running PMS in a Docker may be related to your issue. Check your network settings and file permissions etc. for the Docker container and also all other network settings, just in case something is slowing things down.

You can also try reducing or increasing the _Amount of movies_ to fetch in Global Settings, to see if that helps with the issue. I'm not sure this will help, but it certainly cannot hurt.

Your logs do not show anything out of the ordinary, as far as I can see, but Tommy may see more than I do.

Please set the `What file log level to use (Change only if asked by the devs)` option to silly, before conducting any further tests and provide those logs along with your findings, thanks.

**Comment by ukdtom** [comment]
Please switch file log level to Silly, and restart WebTools-NG

Then reproduce, and upload new set of logs

**Comment by Droppisalt** [comment]
[WebTools-NG_.txt](https://github.com/WebTools-NG/WebTools-NG/files/8680491/WebTools-NG_.txt)

**Comment by Droppisalt** [comment]
[WebTools-NG.log](https://github.com/WebTools-NG/WebTools-NG/files/8680492/WebTools-NG.log)

**Comment by ukdtom** [comment]
According to the log, your server is located on `[2022-05-12 11:19:55.698] [verbose] Checking: https://172.19.0.2:32400`

But we can't connect to it from the workstation running WebTools-NG ?

**Comment by Droppisalt** [comment]
Ahhh that's my Docker's internal IP. The IP to access the server it 192.168.2.70:32400. Is there any way to point it to there instead?

**Comment by ukdtom** [comment]
Nope, I get it from plex.tv

But can't you create a route to it from your current network?

**Comment by Droppisalt** [comment]
Got it! Added my server IP here:
![image](https://user-images.githubusercontent.com/67336980/168198498-20682a87-b846-40eb-9d41-910bdec21844.png)
Now, according to my logs, it looks at https://172.19.0.2:32400, fails and then looks at https://192.168.2.70:32400 and connects successfully

Last question, not related to this but I'm having a hard time editing the values here. I have to click/alt+tab multiple times for it to finally register that I want to input something. Backspace seems to work fine but not entering a new value. Took me a good minute before being able to enter 9 in "Delimiter between columns in CSV file (Use 9 for TAB)"
![image](https://user-images.githubusercontent.com/67336980/168199502-c43c40c3-4116-41e8-9181-e0cc080fbefd.png)

**Comment by trumpy81** [comment]
Being unable to enter the settings is unfortunately a bug. 

You will notice that while on that page, go to Help > About WebTools and then you can edit as normal. Alternatively, if you click outside of the WebTools-NG window to deselect the window and then click on the window, you are able to edit the settings as normal.

It' a very strange bug and not something I have ever seen before, but Tommy is aware of the issue. Unfortunately he has not been able to track it down just yet, but if I know Tommy, he'll find the pesky little blighter ... fingers crossed ... lol

**Comment by ukdtom** [comment]
Actually, I did find it ;)
It was the bloody alert box that stole focus :(

You can find a not yet released fix here:
https://www.dropbox.com/sh/7o2ywjl02z2dby2/AAAcyezuMrCIAsiZvEKiu_3Wa?dl=0

**Comment by ukdtom** [comment]
@trumpy81 

Maybe get @Droppisalt solution over  as a Wiki entry?

**Comment by Droppisalt** [comment]
> 
Sweet! I'll try it out in a few

**Comment by trumpy81** [comment]
Wiki updated here: https://github.com/WebTools-NG/WebTools-NG/wiki/Known-Issues
