### ISSUE TITLE
[BUG] ExportTools Settings cannot input any text at all

### ISSUE THREAD

**Issue by trumpy81** [WebTools-NG/WebTools-NG#488]
**Describe the bug**
Going to ET Settings, I cannot input anything until going to Help > About WebTools, then I can input any text etc.

**To Reproduce**
1. Go to ET Settings
2. Click on any setting.
4. The Text Box will not accept any input
5. Go to Help > About WebTools
6. Return to ET Settings and then you are able to input any text etc.
7. Also noticed that clicking outside the WebTools-NG window to deselect the window and then clicking on the WebTools-NG window again, will allow you to input text.

**Expected behavior**
Should be able to input text without going to Help > About WebTools ... lol

**Desktop (please complete the following information):**
Windows 11 Pro

Applies to v0.3.16 and v0.3.17

**Comment by ukdtom** [comment]
Confirmed, and really strange
