### ISSUE TITLE
[RFE] Wiki request

### ISSUE THREAD

**Issue by ukdtom** [WebTools-NG/WebTools-NG#490]
Could this Reddit thread be turned into a Wiki Page?

https://www.reddit.com/r/PleX/comments/unb2y1/library_issue/

**Comment by trumpy81** [comment]
Added a Hints & Tips page with details of using WebTools-NG and the ExportTools module for new users.

Let me know if this is what you wanted or not, please.

**Comment by ukdtom** [comment]
Perfect as always, Thanks
