### ISSUE TITLE
[RFE] FindMedia - Analyze folder and find media missing from plex server

### ISSUE THREAD

**Issue by Jerrk** [WebTools-NG/WebTools-NG#497]
**Is your feature request related to a problem? Please describe.**
Plex scanning your folders for media does not always find everything. 
A folder might have incorrect permissions, a file may be incorrectly named, a file may be corrupted, etc.

**Describe the solution you'd like**
I would like to be able to analyze a plex library and it's base folder to find media that is missing from the plex server.

**Describe alternatives you've considered**
In the old webtools this used to be possible with the FindMedia Tool, and before that the FindMissing/ListMissing plugin. they no longer work.

**Additional context**
Bring it up to parity with the old Webtools plugin.

**Comment by trumpy81** [comment]
This is no longer possible. With WebTools-NG all calls must go through plex.tv and the Plex API.

There is NO direct access to your server's file system any longer, so it is not possible to scan the file system and compare it to the Plex database as all calls go through the Plex API now.

See this page https://github.com/WebTools-NG/WebTools-NG/wiki/Tips on the Wiki for details on setting up ExportTools to export your library. You would then need to compare the number of files listed by ExportTools to the actual number of files on your server to find any missing or duplicated files etc.

Proper file naming, as per the Plex guidelines, can greatly reduce the number of missing files etc.

I recommend using FileBot to name your files for you automatically.
