### ISSUE TITLE
[BUG] Time/Date output not as expected

### ISSUE THREAD

**Issue by trumpy81** [WebTools-NG/WebTools-NG#502]
**Describe the bug**
I have noticed an oddity with the date format when outputting the Date Added field in ExportTools.

I am not sure if this is a Plex issue or an ExportTools issue?

**To Reproduce**
1. Output a Movies type library with the Date Added level
2. Check the output file

**Expected behavior**
I expect to see a uniform time/date format, but I see two different styles being output.

Global Settings are set to show Short format, but it makes no difference if set to show Full format as the same time/date formats are shown in both cases?

E.G:
2019-00-24 1:10:33
16/07/2018  4:47:12 PM

I should also note that the different formatting also effects the line justification, one being left justified and the other being right justified.

**Screenshots**
![image](https://user-images.githubusercontent.com/12381786/171726922-fe8e532e-756a-46b2-bfd7-30de62473524.png)

**Desktop (please complete the following information):**

Version: 0.3.17.67073d9
Platform: Windows 11 Pro
Architecture: x64

**Sample Output File**
[PlexStation_Movies 4K_Movie_Movies_Test 02_Item 0-36_2022.06.03_5.48.28.csv](https://github.com/WebTools-NG/WebTools-NG/files/8827471/PlexStation_Movies.4K_Movie_Movies_Test.02_Item.0-36_2022.06.03_5.48.28.csv)

**Comment by ukdtom** [comment]
Your file, opened in Libra Office Calc on Windows ;)

![image](https://user-images.githubusercontent.com/4699449/171731552-12a86c3e-1d5e-49bc-9431-048b43d364e1.png)


And from Notepad++

![image](https://user-images.githubusercontent.com/4699449/171731834-77401e75-dd6a-4293-b293-aeafc3dfe72b.png)


So in short, I blame Excel, or ?

**Comment by ukdtom** [comment]
Ohh....Do you use 24 hours clock, or 12?

**Comment by trumpy81** [comment]
I am using a 12 hour clock in Windows, but both of my NAS use a 24 hour clock.

**Comment by ukdtom** [comment]
I knew it, you are a trouble maker, LOL

**Comment by ukdtom** [comment]
And thanks for that, since that makes you a better tester ;)

What's the official for your country?

**Comment by trumpy81** [comment]
Yes I am (a troublemaker) ... lol ... ;p

The default for Australia is Day, Month, Year, Hours, Minutes, Seconds.

Any separator can be used, **- / : .** etc...

**Comment by trumpy81** [comment]
BTW, doing a metadata refresh on this file did NOT fix the Date Added time/date, it is still showing as:

Hotel Transylvania: Transformania | 2022-00-26 10:34:12

I think I'd have to hit the database directly to correct that, if I am not mistaken?

**Comment by ukdtom** [comment]
I meant is the default 12 or 24 hours clock?

And if on the latest PP build, then try a Plex Dance on the movie

**Comment by trumpy81** [comment]
The default for Windows 11 is the 12 Hour clock, although you can probably change that during installation or just after installing Windows.

The default for the Synology NAS is 24 Hour format, but you may change that in Control Panel > Regional Options.

**Comment by ukdtom** [comment]
Excel issue
