### ISSUE TITLE
[RFE] No timestamp in output file

### ISSUE THREAD

**Issue by ukdtom** [WebTools-NG/WebTools-NG#508]
We should have an option to have an output filename without the timestamp and/or amount of items
That way, an export would be static
Ref : https://forums.plex.tv/t/webtools-ng/598539/140

- [x] ExportTools
~~- [ ] plex.tv~~
~~- [ ] DVR~~
~~- [ ] FindMedia~~
~~- [ ] ViewState~~
~~- [ ] Settings~~

**Comment by ukdtom** [comment]
Rethinking here, and only makes sense for ExportTools, AFAICT?

**Comment by ukdtom** [comment]
@trumpy81 Note a new setting has been added to ET Settings page

![image](https://user-images.githubusercontent.com/4699449/177017686-c2b788db-b090-412a-addb-a8e1fec220ad.png)

**Comment by trumpy81** [comment]
Done. Wiki updated!

**Comment by ukdtom** [comment]
New setting

![image](https://user-images.githubusercontent.com/4699449/180573210-d7d77d8f-1dbe-4179-93bd-1fd3ea6a42cd.png)

@trumpy81

**Comment by ukdtom** [comment]
@trumpy81 New build avail on DB
