### ISSUE TITLE
[RFE] Inconsistent Font sizing and spacing

### ISSUE THREAD

**Issue by trumpy81** [WebTools-NG/WebTools-NG#521]
- [x] Home
- [x] Download
- [x] ET
- [x] ET Settings
- [x]  ET Custom Levels
- [x] Plex.TV
- [x] PMS
- [x] PMS Butler
- [x] PMS DVR
- [x] PMS Find Media
- [x] PMS Find Media Settings
- [x] PMS Server Settings
- [x] PMS View State
- [x] Language
- [x] Global Settings
- [x] Global Settings General
- [x] Global Settings Export
- [x] Global Settings PMS
- [x] Global Settings Lib Map
- [x] About

There seems to be a lot of inconsistency in the Font sizing, spacing and placement on each of the pages within WebTools-NG.

Without being too critical, the About Us page is a mess in regards to font sizing, spacing etc...

I would also suggest that a 4 pixel white or transparent border on the top and right hand edges, be placed around the module settings icon, so that it at least has some spacing around it. It does not look correct with the icon hard up against the header and right hand edge of the window. I can adjust that for you if you send me the image ;)

The images below outline some of the inconsistencies.

![Screenshot 2022-07-04 135453](https://user-images.githubusercontent.com/12381786/177084090-15ffc63c-e734-4775-8028-482cf8aae759.png)

![Screenshot 2022-07-04 142218](https://user-images.githubusercontent.com/12381786/177084103-dd5b257c-d617-4b85-a321-9d6e67543fd3.png)

**Comment by trumpy81** [comment]
Also, I just noticed that you spelled Media incorrectly on the Find Media page. There is NO plural for the word media, which means **medias** is incorrect. :)

**Comment by ukdtom** [comment]
Some progress can be fetched from DB link

**Comment by trumpy81** [comment]
Just installed v0.3.18.b00a1d0 and things are looking a lot better :)

The module settings icon on the ExportTools page is great, it has some spacing and the placement in relation to the title etc. is much better, it looks more designed now, rather than being slapped on the page ... lol

Navigation from settings etc. is also much improved :)

Also, I did some minor testing of Find Media and it passed with flying colours :)

I dips me hat to ya ... lol

This line and the last paragraph on the About Us page, could be bolded and/or italicised.

**_A huge thanks goes out to all the people who helped in translating and testing WebTools-NG_**

**_And many thanks to the authors/developers and staff at Plex. We are eternally grateful for your dedication, talent and hard work! And to our friends at POEditor.com, who provide a free translation site because we are an Open-Source project._**

Aside from that, it looks a whole lot better. :)

**Comment by ukdtom** [comment]
Regarding about txt, it comes as one string on the translation site, so changing it would req. me to divide it into smaller chunks => more work for translators.

So that will not happen right now, since as is, only a few languages are translated 100 %

**Comment by ukdtom** [comment]
Hopefully, all is fixed now incl. misspell

Can't get more done before vacation, and closed this one

If you find more, please open a new GHI, since this one is getting crowded ;)

New binaries are avail for testing on DB

Denmark signing out for a short vacation
