### ISSUE TITLE
[BUG] Wiki page misleading

### ISSUE THREAD

**Issue by ukdtom** [WebTools-NG/WebTools-NG#525]
On this page, unless I'm getting it wrongly, you state that we have to launch WT-NG with the token?
https://github.com/WebTools-NG/WebTools-NG/wiki/Install

So Windows sample...

After download, and initially clicking on the exe, WT-NG is installed on windows!

So simply search for it, and maybe create a shortcut, or pin to like taskbar

![image](https://user-images.githubusercontent.com/4699449/177222337-0ceacc75-d0e6-471d-95c4-fbe26dc9bae4.png)

The token param is only needed for lazy people, that doesn't care about security, and as such create a cmd file, and for future use, if I ever manage to allow WT-NG to run scheduled tasks ;)

**Comment by ukdtom** [comment]
And it actually get's installed here:

C:\Users\<USER_NAME>\AppData\Local\Programs\webtools-ng

And even comes with an uninstaller ;)

**Comment by trumpy81** [comment]
The Wiki describes opening the WebTools-NG program from the command line and using the token to auto login.

The normal method of installation is on the first line:
> To install WebTools-NG, simply download the package required for your PC/Laptop's OS and double click on it.

There is a line missing from the top of the page. I moved things around a bit and deleted it without realising.

I will work on it some more ... lol

**Comment by trumpy81** [comment]
Wiki updated!

Hopefully, the Installation page makes a bit more sense now :-|
