### ISSUE TITLE
[BUG] Wiki page about

### ISSUE THREAD

**Issue by ukdtom** [WebTools-NG/WebTools-NG#536]
Says:

`WebTools-NG will operate from any location in the world, that has an internet connection, so you do NOT need to be local to your Plex Media Server machines at all`

But library mapping needs a direct connection ;)
So as of now, Find Media only works if we can map/mount the file system of the PMS

Other modules might req. the same in the future, like maybe a subs module ;)

**Comment by trumpy81** [comment]
That's a good point.

I have removed that line from the About page.

**Comment by ukdtom** [comment]
Perfect
