### ISSUE TITLE
[RFE] ET Library output needs the Library Title in 1st Column

### ISSUE THREAD

**Issue by trumpy81** [WebTools-NG/WebTools-NG#538]
**Is your feature request related to a problem? Please describe.**
If you choose to output your library definitions, then a lot of information is output, but sadly the Library Title is located at the end (and sometimes hidden until the window is scrolled) and it is not always easy to figure out which library is which, given the amount of useful data that is output.

**Describe the solution you'd like**
I would like to see the Title of the library being output, preferably in the first column, so that each library is clearly identified.

**Comment by ukdtom** [comment]
Currently sorted by first letter in the label, bur I see and ack your point ;)

**Comment by ukdtom** [comment]
New build avail on DB @trumpy81

**Comment by trumpy81** [comment]
Excellent, job done :)
