### ISSUE TITLE
[BUG]?? Date/Time Settings Duplicated

### ISSUE THREAD

**Issue by trumpy81** [WebTools-NG/WebTools-NG#541]
**Describe the bug**
In the Latest Build, The `Select Date/Time format`, `Date Style` and `Time Style` settings are shown on `Global Settings > General Settings` and `Global Settings > Export Settings`.

**Expected behavior**
I suspect that they should only appear in one location?

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro

**Comment by ukdtom** [comment]
Indeed, and belongs to the export one, and when I couldn't find it there, I created #531 and added to global

Will remove from there again, SIGH
