### ISSUE TITLE
[BUG] Export Art & Posters NOT honouring the Dimension settings

### ISSUE THREAD

**Issue by trumpy81** [WebTools-NG/WebTools-NG#542]
**Describe the bug**
I'm not sure if this is an ET issue or a Plex issue.

Exporting art results in the configured dimensions being ignored. The files are named with the dimensions in the filename, but upon opening the file in an image editor etc. the dimensions differ.

The configured dimensions for art are 1920\*1080, but the actual image dimensions as output, vary a great deal, from 1280\*720 to 3413\*1920.

See the image below, it shows the filename as output and the actual dimensions of the image.

E.G.
![explorer_3Qco96XXuz](https://user-images.githubusercontent.com/12381786/179644344-1347f2cb-f92a-47fe-b4d8-fe0f7a0715b2.png)

Exporting Posters, the setting is configured to 200\*300, but the output files are all 300\*450. It seems the width setting is being ignored and the height setting is being confused with the width setting. It appears that the image aspect ratio is being used to determine the height instead.

**Expected behavior**
I expect the images to be in the resolution set in the ExportTools settings.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 
**WebTools-NG.json**
[WebTools-NG - Copy.zip](https://github.com/WebTools-NG/WebTools-NG/files/9136763/WebTools-NG.-.Copy.zip)

**Logs**
[WebTools-NG.log](https://github.com/WebTools-NG/WebTools-NG/files/9136766/WebTools-NG.log)

**Comment by ukdtom** [comment]
It's how PMS does it sadly...

In the Tooltip

![image](https://user-images.githubusercontent.com/4699449/179865338-5abed5ff-cd9e-45e7-b305-6a21e6d18d14.png)

**Comment by ukdtom** [comment]
When said, in the Wiki under export, we do not tell people how-to export posters and arts, AFAICT?

**Comment by trumpy81** [comment]
There is a tip on the Wiki informing the user to use an \* asterix when defining the Width\*Height dimensions, but nothing beyond that. I will correct that once this is sorted out.

For Posters & Art, using comma separated dimensions causes multiple images to be output, one for each dimension specified.

For Posters, the dimensions are being reversed. If I specify 200\*300, then the posters are all output at 300\*450, but if I specify 300\*200 then the posters are output at 200\*300.

The dimensions also change for Art. When the Setting reads 1080\*1920, then the majority of the artwork is output at 1920\*1080 or less, but NOT more than 1920\*1080. If you reverse the Settings dimensions, then the output artwork dimensions are all over the place, less and more.

So the dimensions need to be written as Height\*Width and not as Width\*Height as they are now.

I have also noticed that sometimes, the Limit Export dialogue will show the start item to be equal to the end item, even though it will output from 0 if you do not change anything.

![Screenshot 2022-07-21 002837](https://user-images.githubusercontent.com/12381786/180007754-ad9b4f26-b78c-4fcf-bb6d-fa3b7ecd95e2.png)
.

**Comment by ukdtom** [comment]
And as usual, feel free to reopen if something is still wrong with the newest build
