### ISSUE TITLE
[RFE] Export posters for Seasons and shows when

### ISSUE THREAD

**Issue by ukdtom** [WebTools-NG/WebTools-NG#550]
When exporting posters for an episode, we should look into exporting season and show posters as well

Ref: https://www.reddit.com/r/PleX/comments/umxkrb/comment/ihz5b8r/?utm_source=reddit&utm_medium=web2x&context=3

**Comment by kiwichick888** [comment]
Export for Show posters is already possible but I would absolutely love it if we could also export Season posters.
