### ISSUE TITLE
[RFE] Exporting posters and Arts into tree

### ISSUE THREAD

**Issue by ukdtom** [WebTools-NG/WebTools-NG#551]
Maybe consider an export option, so we export into a file tree, like

We are exporting `The 100/Season 01/S01E01` so we create those directories, and put the exported files in those

Another option could also be to via the library mapping to export into the source files location ?
Like: https://support.plex.tv/articles/200220717-local-media-assets-tv-shows/

**Comment by kiwichick888** [comment]
Oh I Iove this idea. Exporting to a tree structure would be great!!!

**Comment by ukdtom** [comment]
Dropped idea about writing to user media store.

Too dangerous, since could lead to overwriting files not intended

But tree export done, and will be part of next release
