### ISSUE TITLE
[BUG] Media Resolution Type Not Reporting SD. 

### ISSUE THREAD

**Issue by BRAYDIN72** [WebTools-NG/WebTools-NG#555]
**Describe the bug**
[BUG] Media Resolution Type Not Reporting SD.  If the files meta data shows it is SD an export will leave a blank in that field of the CSV. Prior to 1.0 It would populate the SD.  if the Metadata list it as 480, it will fill the field properly.

**To Reproduce**
1. Go to Custom Level 
2. Create a custom Level with Media Resolution as a field
3. Export the file.
4. Import into Excel
5. Look for Blank fields.

**Expected behavior**
SD should populate 

**Screenshots**

**Desktop (please complete the following informat
[WebTools-NG.zip](https://github.com/WebTools-NG/WebTools-NG/files/9222300/WebTools-NG.zip)
ion):**
 - OSWindows 11

**Additional context**

**Logs**
Please provide WebTools-NG logs in a zip
[WebTools-NG.zip](https://github.com/WebTools-NG/WebTools-NG/files/9222298/WebTools-NG.zip)

**Comment by ukdtom** [comment]
Let me guess, you are using Excel?

![image](https://user-images.githubusercontent.com/4699449/181835602-6991f740-4769-4ee4-b5a4-edcb77a79314.png)

Above is your attachment, opened with LibreOffice Calc

So maybe MS Excel has the column formatted as numbers only?

**Comment by BRAYDIN72** [comment]
If you look at the actual delimited file there is nothing there in the newest but the oldest shows the SD I think you imported the older pre 1.0 file

**Comment by BRAYDIN72** [comment]
I'm not sure what its doing but it is excel. Went back and found the sd in the CSV file and every time I tried to import it , the SD ones were blank. 


> If you look at the actual delimited file there is nothing there in the newest but the oldest shows the SD I think you imported the older pre 1.0 file

yeah it's excel.

**Comment by ukdtom** [comment]
@trumpy81 

Another pin to the Excel grave for your Wiki ;)

**Comment by trumpy81** [comment]
Yeah, I gave up on Excel a little while ago ... it sux ... lol

I will add a note to the Wiki to check the raw data first, then use Libre Office ... lol

**Comment by trumpy81** [comment]
Wiki has been updated :)
