### ISSUE TITLE
Andy check time ;)

### ISSUE THREAD

**Issue by ukdtom** [WebTools-NG/WebTools-NG#557]
Please fetch latest build on DB

If prompted to update EN lang, then don't

Do test the following:

* https://github.com/WebTools-NG/WebTools-NG/issues/547 (Enhancement)
* https://github.com/WebTools-NG/WebTools-NG/issues/552 (Enhancement)
* https://github.com/WebTools-NG/WebTools-NG/issues/550 (Enhancement)
* https://github.com/WebTools-NG/WebTools-NG/issues/551 (Enhancement)

Note that ET Settings has two new options for Posters & Arts
Note that when exporting episodes posters and arts, there's more things to select for your custom level

And please don't update Wiki yet, since not released ;)

And do let me know the outcome

**Comment by trumpy81** [comment]
1. Checked link is present and functional
2. Checked Export Posters and Art in Original Size function
3. Checked Export Posters and Art for TV Shows function
4. Exporting to tree is functional

First of all, the word Art does not have a plural. It should be `Posters and Art` ... NOT `Posters and Arts`.
Secondly, no need to include a directory named `tree` in the folder output structure.
Thirdly, I would like to see the export of Posters and Art without the tree structure, as an option, if possible. Perhaps another setting on the settings page?

Otherwise, everything looks good :)

**Comment by ukdtom** [comment]
> First of all, the word Art does not have a plural. It should be Posters and Art ... NOT Posters and Arts.

Noted, and will change, thanks

> Secondly, no need to include a directory named tree in the folder output structure, unless there is an option?

If you haven't selected to export as tree, then it goes into a directory named flat, that resample the old export way

> Thirdly, I would like to see the export of Posters and Art without the tree structure

Deselect export as tree should do that, or?

**Comment by trumpy81** [comment]
There is no option to select tree or not, unless I missed it?

**Comment by ukdtom** [comment]
Wow, you are correct here.....

It's a manual JSON edit of the key named:
`ET.ExportPostersArtsTree`

Will add a GUI for that in ET Settings ;)

**Comment by trumpy81** [comment]
👍 Excellent

You had me going for a bit there ... thought I was losing it ... lol

**Comment by ukdtom** [comment]
Standby for new build that is currently cooking

ETA 6 min

**Comment by ukdtom** [comment]
New build avail on DB

![image](https://user-images.githubusercontent.com/4699449/182050130-b0160125-836e-4646-b9cd-698196b9d03e.png)

**Comment by ukdtom** [comment]
Also note, that if exporting in original size, it'll be a lot faster, since no transcode is needed

**Comment by trumpy81** [comment]
Installed new build and tested export to tree.

Setting is NOT working, it outputs to tree regardless.

Do I need to reset the json?

**Comment by ukdtom** [comment]
Should not be needed, I'll look into it, but bedtime now ;)

**Comment by trumpy81** [comment]
OK ... TTYL

**Comment by ukdtom** [comment]
Went ahead, and sadly can't reproduce :(

So STD and logs needed (In Silly mode)

**Comment by trumpy81** [comment]
I messed around with the .json earlier and now it seems to be working as expected.

Now I get a flat/arts folder ... it should flat/art folder ;)

**Comment by ukdtom** [comment]
> Now I get a flat/arts folder ... it should be a flat/art folder ;)

https://github.com/WebTools-NG/WebTools-NG/commit/5c7a9f3033e1eb77fdb714dcd8f95a1f2e28683d
