### ISSUE TITLE
[RFE] Add tmdb to credits

### ISSUE THREAD

**Issue by ukdtom** [WebTools-NG/WebTools-NG#575]
YES !!!!

We got an API key for free for tmdb as well :)

They said:

Hello developer. Your project's API key has been approved, with conditions:

************ 

You must display attribution saying "Information provided by TheTVDB.com. Please consider supporting them.", with the last part linking directly to our [subscription page.](https://u10505776.ct.sendgrid.net/ls/click?upn=xMYYCP13hVd-2BZPpbVcMPHeLXfv-2BPRdIsKm2qSeirIHi7kH9am8IxD-2BavFbeqGqIXniVL_KeC-2BJSmh7Vns5QA7V6XlzXXL0Z5AIcfhh46gftOjY-2BEBc3vGik5m-2FjOe2CDYtBbBGHuhvM6lOOZLbrgWJoV-2F7uuQCwrOrQYxEODu604MeCRmfiVdW9LEgj42H6iXocCJwBLQpwY7V56Ntt288e2T38RxvzWU1BYw3Xf7e7HyEAxojL0wCYLWegaBnmSHGKSmmpUT6BaN9cJGPKGDDaoiiA-3D-3D) If your project is unable or unwilling to display attribution, please create a support ticket to discuss further.
Please review our [documentation](https://u10505776.ct.sendgrid.net/ls/click?upn=xMYYCP13hVd-2BZPpbVcMPHafUthCP3x-2B5VDMg2xIzustDwZC8vNAgt9o8t2y0uKpe7BqZ_KeC-2BJSmh7Vns5QA7V6XlzXXL0Z5AIcfhh46gftOjY-2BEBc3vGik5m-2FjOe2CDYtBbBhYqcbxlMLgGXjrCKan5PM9ePOhGKi0b845iTmTdtHnJiWdRrnt1tLOQMSumG4eQZJIrgqd621UH-2FPvYffYgDtfbAJ2Z5l4tFflGGmioSmoRbzKZ7zEuBMO8dVFoHLBOfRORbmy6wmMN1fEJhidj1bA-3D-3D) and [create a support ticket](https://u10505776.ct.sendgrid.net/ls/click?upn=xMYYCP13hVd-2BZPpbVcMPHUvnWmyUF4fH-2BFtUn4cEuS4vZf0zjVnCZF748t8G-2BNVB3I00_KeC-2BJSmh7Vns5QA7V6XlzXXL0Z5AIcfhh46gftOjY-2BEBc3vGik5m-2FjOe2CDYtBbBtYIW3rUp45hwIeT1uCuxWkV83Bk0qQEOjnQVsXmLQBZlR6Xkp6Etywc6qcfEnJZ2LSM-2FFRSY5vFqhLkmyVYQh2SgKUVMrm-2F1QQZgJp77e0JvXVfaslZHwaRFsDuMI3zvWZTY7CjCPWSi-2B5PnK9j-2BiA-3D-3D) if you require any assistance.

***************************

So we need to add this to both the Wiki/Readme as well as to the App itself

I'll handle the app, so if you could handle the wiki it would be very nice @trumpy81 ?

**Comment by ukdtom** [comment]
And their logo, like on the others is mandatory ;)

**Comment by trumpy81** [comment]
The Wiki ReadMe.md and Wiki About Us pages have been updated to include the TVDB logo etc...

**Comment by ukdtom** [comment]
Fixed
