### ISSUE TITLE
[RFE] Chose bytes instead of bits for file sizes

### ISSUE THREAD

**Issue by Lightningblade** [WebTools-NG/WebTools-NG#581]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like to have a logfile size selector  in General Settings that uses bytes as size.

**Describe alternatives you've considered**
Have both bit and bytes as option to have backwards compatibility.

**Additional context**
![image](https://user-images.githubusercontent.com/30607152/188001305-36154070-7d99-47dd-af15-a43953d68b95.png)

**Comment by ukdtom** [comment]
I sadly fail to see the value here...

And most users knows 10Mb, but would not know 10240

So please provide a use case

**Comment by Lightningblade** [comment]
The Giga Mega Kilo prefixes are fine. I just want to be able to specify the size in GB/MB/kB not Gb/Mb/kb

**Comment by ukdtom** [comment]
Sadly not native English speaking here, so you completely lost me, sorry

Are you talking about it says `Gb` instead of `GB` ?

**Comment by Lightningblade** [comment]
8 bit (b) is 1 byte (B).
The application right now uses bits (b) as metric for the log file size (Mb). This is possible, however, since most filesystems and storage devices (and even RAM) can not manipulate bits at a time, but rather access and store Bytes (B) it is an industry standard to measure files in bytes. This means that the 10Mb, as seen in the picture, are 1.25MB.

**Comment by ukdtom** [comment]
DO NOT EDUCATE ME!

Code:

```
setLogLevelSize: function(value){
        let size = '';
        switch(value)
        {
          case "1Mb":
            size = "1048576";
            break;
          case "2Mb":
            size = "2097152";
            break;
          case "4Mb":
            size = "4194304";
            break;
          case "8Mb":
            size = "8388608";
            break;
          case "10Mb":
            size = "10485760";
            break;
          case "20Mb":
            size = "20971520";
            break;
          case "40Mb":
            size = "41943040";
            break;
          case "60Mb":
            size = "62914560";
            break;
          case "100Mb":
            size = "104857600";
            break;
          case "200Mb":
            size = "209715200";
            break;
          default:
            size = "1048576"
        }
```

**Comment by ukdtom** [comment]
If still a need for you, create a PR with the req. changes
