### ISSUE TITLE
[BUG] Export Episodes containing Export Season Posters fails to proceed

### ISSUE THREAD

**Issue by trumpy81** [WebTools-NG/WebTools-NG#586]
**Describe the bug**
If you want to output TV Episodes and you have a Custom Level containing Export Season Posters and/or Export Show Art, then the export will fail to proceed and the status will stay at 0 of XXX.

**To Reproduce**
Steps to reproduce the behaviour:
1. Choose Export Type to be TV
2. Choose Sub Type to be TV Episodes
3. Choose a Custom Level containing Export Season Posters and/or Export Show Art
4. Export Media
5. The export status will stay at 0 of XXX and will not proceed.

**Expected behaviour**
I would expect a warning about posters and art being unable to be exported and the export to proceed, without any art or posters.

Alternatively, for TV Episodes -> Custom Levels, one should NOT be able to select or add Export Season Posters or Export Show Art or Export Posters or Export Art.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - WT-NG v1.1.0

**Logs**
[WebTools-NG.log](https://github.com/WebTools-NG/WebTools-NG/files/9483773/WebTools-NG.log)

**Comment by ukdtom** [comment]
Just tried, and working fine here :(

Maybe more info, or a video?

**Comment by trumpy81** [comment]
Here's a short video and log for ya ;)
https://user-images.githubusercontent.com/12381786/188317367-b03064ef-053c-4343-a035-8b4438e26eeb.mp4

[WebTools-NG.log](https://github.com/WebTools-NG/WebTools-NG/files/9484830/WebTools-NG.log)

**Comment by ukdtom** [comment]
Hmmm.....

I see a different error, and my logs shows an 401 error, due to the fact, that I forgot to set the header

**Comment by ukdtom** [comment]
G-Drive updated with never builds.

Please check if working now, and if not, I need SILLY logs ;)

**Comment by trumpy81** [comment]
I tried the new build the same way as shown in the video, but there is no change, the export does not proceed.

**Comment by ukdtom** [comment]
Then I sadly needs silly logs, due to the fact that I exported from your box okay ;)

**Comment by trumpy81** [comment]
I just tried to get silly logs, but very little was output, probably because the export did not proceed.

Here is what I have though:

[WebTools-NG.log](https://github.com/WebTools-NG/WebTools-NG/files/9485657/WebTools-NG.log)

**Comment by ukdtom** [comment]
Please clear logs, then shutdown WT-NG, followed by a reproduce

One of the important things in the logs are, that when started, it logs all your settings (But leave out sensitive stuff)

**Comment by trumpy81** [comment]
Okay I will try again. I am exporting with just Export Art and Export Posters and that is working as expected.

I will reset and see if I can grab the logs again.

**Comment by trumpy81** [comment]
I tried again but nothing was output at all. The various folders were created including a seasonposters folder, but nothing else.

Here is the log:

[WebTools-NG.log](https://github.com/WebTools-NG/WebTools-NG/files/9485677/WebTools-NG.log)

**Comment by ukdtom** [comment]
What happens, if you start export with a start of 500 and an end of 505?

**Comment by trumpy81** [comment]
Hmmm ... that actually worked. The list of episodes was output, as was the seasonposters, showart and showposters.

Could it be failing because of the characters in my first library title, ```$#*! My Dad Says```

**Comment by trumpy81** [comment]
I just tried running the export starting with 18 and ending with 500. It worked as expected.

I ran the export again starting with 10 and ending at 500 and it failed to work at all.

That seems to indicate that it does have a problem with the first series title.

**Comment by ukdtom** [comment]
Correct, and will look into that

**Comment by ukdtom** [comment]
`*` is an illegal character, and forgot to sanitize it ;)

Standby for a new build

**Comment by trumpy81** [comment]
New build installed and all appears to be working now :)

**Comment by ukdtom** [comment]
It's a txt file, and if you open it in notepad, you'll see that for that show, the show art is missing, and PMS returns a 404 error
