### ISSUE TITLE
[RFE] Wiki Find Missing Episode

### ISSUE THREAD

**Issue by ukdtom** [WebTools-NG/WebTools-NG#588]
Hi Andy

In the soon to be released version of WT-NG, we introduce the new Export Level "Find missing episodes"

I do consider this a VERY cool feature, that makes WT-NG stand out, so I was wondering if you somehow could make it stand out in the Wiki?

Req:

* You must run a Show Library with the newest Plex Agent
* You must have refreshed all metadata when upgrading from older python based version

Fact:

For now, in this first release, we only support tmdb lookup's, but a priority for the next release is:

* Lookup defaults for a Show library, and use that if no exception is made
* Support the following:
  * tmdb
  * tvdb
  * tvdb aired
  * tvdb DVD

**Comment by trumpy81** [comment]
The Wiki Find Media page has been updated.

Let me know your thoughts please.

**Comment by ukdtom** [comment]
Well,` Find Media` and `Find missing Episodes` are two completely different things

First one needs local access to filesystem, and is a compare between database and file system
Second one doesn't use the file system, but is a compare between a show library, and TMDB

As such, I don't thing they should be merged in the Wiki

**Comment by trumpy81** [comment]
Both processes use the Find Media module, so there is no way to separate them, despite the differences under the hood.

I could create another page for Find Missing episodes, but it would be a duplicate of what is already there.

Let me know how I should proceed.

**Comment by trumpy81** [comment]
Just to be clear, to use Find Missing Episodes, you simply select a TV Show library to scan and click on Run, correct?

There are no other buttons or settings that need to be setup or clicked on, if there is, then I am not seeing them?

**Comment by ukdtom** [comment]
No, It's a new level for Export Tools when show is selected ;)

**Comment by trumpy81** [comment]
No wonder I could not find it ... doh!

I'm in the wrong module completely ... lol

I tried it for real this time, and I see a lot of mismatched counts on a lot of shows, yet when I check what I have and then check TVDB all appears to be correct. The TMDB is not the most reliable for TV Shows though ... lol

[ROGStrix_TV Shows_TV_TV Shows_Find Missing Episodes_Item 0-332_2022.09.05_10.16.09.csv](https://github.com/WebTools-NG/WebTools-NG/files/9489748/ROGStrix_TV.Shows_TV_TV.Shows_Find.Missing.Episodes_Item.0-332_2022.09.05_10.16.09.csv)

I will have to go and check all of my series again now ... oh boy!

**Comment by ukdtom** [comment]
Before the new agents, tvdb was the default, but with the new ones, it's tmdb, thus why I started with that.

But as said, tvdb is on the roadmap ;)

And the ones in your sheet that has no tmdb id found, are most likely badly named, or never had their metadata refreshed after you switched to the new agents

And still, does give a nice overview about what shows are still running

**Comment by trumpy81** [comment]
<--- Wipes egg off face and corrected the Wiki ... lol

Thoughts please.

Yeah I knew about the switch, but still cannot fathom why Plex did that. The TVDB is still the better option, but it has lots of anomalies as well.

I do like seeing the status of the various TV Shows, cancelled, ended, etc...

**Comment by ukdtom** [comment]
Before the new agents, tvdb was the default, but with the new ones, it's tmdb, thus why I started with that.

But as said, tvdb is on the roadmap ;)

**Comment by ukdtom** [comment]
One API is free for commercial use, the other is not

Does that perhaps share some light on this ;)

**Comment by trumpy81** [comment]
Yes that does make sense now that you mention it, at the time though, TVDB was not asking for payment ... lol

**Comment by ukdtom** [comment]
True

And since the Wiki page is in place now, I'll close this on

Thanks
