### ISSUE TITLE
[BUG] 1.1.1 Find Missing Episodes Stalls after X shows and does not proceed

### ISSUE THREAD

**Issue by trumpy81** [WebTools-NG/WebTools-NG#591]
**Describe the bug**
Attempted to `Find Missing Episodes`, but the process stalled after 55 Shows (from 332). The log seems to indicate an episode mismatch and also a response error, so I am not sure exactly what the issue is.

I checked the show in question (Constantine) on the TVDB, but could not find any mismatch in the episodes. The Show is not listed on TMDB as far as I can tell (didn't look hard enough ... doh!).

I ran the process a second time and it stalled at the same point.

**To Reproduce**
Steps to reproduce the behaviour:
1. Use ExportTools Find Missing Episodes on my TV Shows library
2. Watch the process stall

**Expected behaviour**
The process should continue to the end of the list of TV Shows.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro

**Logs**
[WebTools-NG.log](https://github.com/WebTools-NG/WebTools-NG/files/9579238/WebTools-NG.log)

**Second Log**
[WebTools-NG - 02.log](https://github.com/WebTools-NG/WebTools-NG/files/9579286/WebTools-NG.-.02.log)

**Comment by ukdtom** [comment]
Bad media naming ;)

In the XML for your TV SHow, it shows the following guids

```
<Guid id="imdb://tt0081846"/>
<Guid id="tmdb://1430"/>
<Guid id="tvdb://74995"/>
<Guid id="tvdb://282121"/>
```

Notice there's two entries for tvdb !

First one is the correct one, and the other one is invalid

You named your an episode as:

`Cosmos\Season 01\Cosmos - S01E01 - The Shores Of The Cosmic Ocean.mp4`

Should be named as:

`Cosmos (1980) {tvdb-74995}\Season 01\Cosmos - S01E01 - The Shores Of The Cosmic Ocean.mp4`

tvdb hint is optional, but year is mandatory, since PMS got confused, and matched twice

Might have to do the Plex Dance after a rename

**Comment by trumpy81** [comment]
Apart from `Cosmos (1980) {tvdb-74995}`, which was not needed at the time and is still not needed (see TVDB), and the episodes are named correctly as far as I can tell.

282121 on the TVDB actually matches to a Movie = Winding and Hunter Cope (person) so it seems like a TVDB issue?

I have no idea why that would be present in Plex though?

**Comment by ukdtom** [comment]
Sadly no idea, and hold back on the renaming, since you are correct here....

I should not stop, but note in the missing column, and then continue to the next show...

Standby

**Comment by trumpy81** [comment]
Is there a way to remove the errant TVDB ID without Plex Dancing the show?

**Comment by ukdtom** [comment]
Sadly, AFAIK, not possible :(

And building a new version, so stand by here

**Comment by ukdtom** [comment]
New build avail

Please try it, and report back

**Comment by trumpy81** [comment]
Latest build installed and tested and still stalls at the same point (Constantine).

**Comment by ukdtom** [comment]
New build avail

This time I count the actual guids, and if more than one for a provider, I skip the show and log an error. then continue to the next one

**Comment by trumpy81** [comment]
Latest build installed, but now it is stalling at show 171 of 332.

If it is failing at [O.J.: Made in America](https://thetvdb.com/movies/oj-made-in-america), it is listed as a Movie on TVDB, but it is no longer listed as the 5 part mini series that it was when I added that show to the library. My episode naming followed the naming shown at the time.

The mini series is listed on the TMDB though. The TMDB does not list the specials at all.

[WebTools-NG.log](https://github.com/WebTools-NG/WebTools-NG/files/9584375/WebTools-NG.log)

**Comment by ukdtom** [comment]
Well, at least your data covers every edge case avail :-)

New build avail for download.
More logging in case of an error, as well as hopefully will continue now to next show

**Comment by trumpy81** [comment]
> Well, at least your data covers every edge case avail :-)

That is only because my library is very old and there have been lots of changes since it was created  :^p

Latest build installed, but it still stalls at item 171 of 332.

**Comment by ukdtom** [comment]
Darn...tweeked it again, so a new build

**Comment by trumpy81** [comment]
I am not seeing a new build anywhere?

**Comment by ukdtom** [comment]
Heh, I thought you used the G-Drive link ;)

I did a manual build on my Windows box, and only posted a win build

https://drive.google.com/drive/folders/1gqXUacmdZ1LZWHmWqnLol1fE1ouZfjzG?usp=sharing

**Comment by trumpy81** [comment]
I used the dropbox link, but even so, the build on Google Drive is the same as the build I used above.

> [2022-09-17 01:27:44.739] [info]  [main.js] Starting WebTools-NG Version: 1.1.1.afb52ce

**Comment by ukdtom** [comment]
Dropbox has been emptied some time ago!

And above from G-Drive is indeed the newest, so did you try that?

**Comment by trumpy81** [comment]
Also, with O.J., I discovered that it was matched with the original Plex agents on my DiskStation server, but it was matched with the Plex TV Series agents on PlexStation and ROGStrix. Not sure how that happened ???

I also found that the Plex agent does not really match the show either. There is no date for the episodes, no Titles or Sort Titles and no summary for any of the episodes either. This information does exist on the TMDB, so I am wondering why Plex is not pulling that info down.

Also, when I ViewXML, there are no DB GUID's listed at all ??

**Comment by trumpy81** [comment]
Yes I already used that version, as I showed with the log snippet.

**Comment by ukdtom** [comment]
> Also, when I ViewXML, there are no DB GUID's listed at all ??

I only have access to ROGStrix, but it does show the Guids!

Remember we do not look at an episode, but at the show!

**Comment by ukdtom** [comment]
Hmmm....And when doing a manual build, rev number doesn't change :(

Note to self....don't do that again

Standby, kicking off a github build

**Comment by trumpy81** [comment]
That link fails for me ... Also I do not know how to ViewXML at the show level, I can only do it from an episode.

**Comment by ukdtom** [comment]
Please go here:

meet.google.com/ady-czch-xrp

**Comment by trumpy81** [comment]
OK, I installed the Google Drive version and ran it. The export succeeded this time.

[WebTools-NG.log](https://github.com/WebTools-NG/WebTools-NG/files/9589331/WebTools-NG.log)

All my other episodes for other series show the GUID's even for an episode, but O.J.: Made in America does not show any GUID's for any of it's episodes on any of my servers??

**Comment by ukdtom** [comment]
Please join my Google meeting, and I'll show you

**Comment by trumpy81** [comment]
Trying to join now, but nothing but a spinner??

**Comment by ukdtom** [comment]
DArn....left too early...

Do provide TW id/pwd here

**Comment by trumpy81** [comment]
513 655 172
me6rpq7z

**Comment by ukdtom** [comment]
Andy

Lost you...My TW says I'm not on a payed version, and cuts me off :(

**Comment by ukdtom** [comment]
But the trick here is when looking at an episode, to grap the granparentkey, and replace with that in the url

**Comment by trumpy81** [comment]
Yeah I can do that ... just have to remember it now ... lol

**Comment by ukdtom** [comment]
And your final log now shows it's working as expected, so huge thanks for helping out here.

**Comment by trumpy81** [comment]
No problem ... I am glad you were able to get it working :)

**Comment by trumpy81** [comment]
I will update the Wiki now?

**Comment by ukdtom** [comment]
I do think this is a cool feature, that can be useful for lots of people

**Comment by ukdtom** [comment]
Yes, do go ahead with the Wiki

**Comment by ukdtom** [comment]
And closing, since fixed ;)

**Comment by trumpy81** [comment]
For sure ... it has opened my eyes as far as missing episodes is concerned and it's handy to know a shows status, ended, continuing etc...

**Comment by trumpy81** [comment]
Just noticed something strange. If I delete O.J.: Made In America, Optimise Database and Clean Bundles and then re-add it to the library, there is no change in matching at all. The show has no episode titles or summary etc. but is matched.

If I add the same show/files to a new test library, it matches and shows the correct episode titles, summary etc... 

This is true for all 3 of my servers.

So, Plex is retaining some or all of the info in that library related to O.J.: Made In America and will not release it.

We need a 'Delete Show Completely' button so we can fix this crap ... lol

**Comment by ukdtom** [comment]
Steps are:

* Remove O.J files away
* Refresh library
* Empty trash
* Optimize database
* Clean bundles
* Put back in O.J. files
* Refresh library

**Comment by trumpy81** [comment]
I did that, except for the empty trash step, I emptied trash after clean bundles.

So, I followed your steps exactly on all 3 servers, but it made no difference at all. The show matched, but there is no titles, sort titles, dates or summary on any of the servers for that show.

I also added {tmdb-66738} to the folder name, but that made no difference either.

Had a scare with my DS1815+, the Alert LED started flashing, but I had no error or warning messages at all. I thought it may have been a failed CPU (Known issue with this model NAS) so I reported it to Synology.

Just checked and now the Alert LED is NOT flashing .... beats me what the issue was/is ... lol

**Comment by ukdtom** [comment]
Try and name the folder:

`O.J. Made in America (2016) {tmdb-66738}`

Then, after the plex dance, edit the show, and under advanced, select that you match tmdb

![image](https://user-images.githubusercontent.com/4699449/190862268-b4049971-bf68-441f-a9fc-644c138ffdc6.png)

**Comment by trumpy81** [comment]
I set the episode ordering to The Movie Database as you suggested, fix matched the show and hey presto the titles, sort titles etc... are now populated.

It even fixed the error in the .csv.

Thanks for that.

Now I only have Through The Wormhole and Wonders Of Life that show errors, that shouldn't show errors.

I am not sure why they show errors though as they are properly matched etc.

Any ideas?

**Comment by ukdtom** [comment]
Try and name the show folder:

`Through the Wormhole (2010) {tmdb-32900}`

Then do the Plex Dance on it

Your show currently only has a tvdb id, and no tmdb

In general, always as a bare minimum, make sure show folder contains the (YEAR)

**Comment by ukdtom** [comment]
And only looked at above, bit suspect it's the same for the other one

**Comment by ukdtom** [comment]
The other show has two tvdb id's

`/library/metadata/206233`

```
<Guid id="imdb://tt2699374"/>
<Guid id="tmdb://46627"/>
<Guid id="tvdb://253425"/>
<Guid id="tvdb://276322"/>
```

Either try a Plex Dance, or set show to tmdb in adv.

**Comment by trumpy81** [comment]
All I did was edit each show and set the episode ordering to The Movie Database, then Fix Match and now neither show has an error in the .csv file :)
