### ISSUE TITLE
[RFE] Find Missing Episodes and episodes in the future

### ISSUE THREAD

**Issue by ukdtom** [WebTools-NG/WebTools-NG#607]
We should not consider episodes, that has not yet been aired

- [ ] TMDB
- [x] TVDB

Forum thread: https://forums.plex.tv/t/webtools-ng/598539/162?u=dane22

**Comment by ukdtom** [comment]
@trumpy81 

New release on G-Drive, and also note new setting in ET

![image](https://user-images.githubusercontent.com/4699449/191618658-32b0f476-b7ee-4774-bcdd-a6dcd4c1b049.png)


Please test, and check changelog for new stuff here:
https://github.com/WebTools-NG/WebTools-NG/blob/master/CHANGELOG.md

**Comment by ukdtom** [comment]
Darn, fails with tmdb :(

**Comment by trumpy81** [comment]
That's not good, fix it! ... lol  :^p 

Wiki has been updated!

BTW, Project Binky and Shannons Club TV (the 2 shows I had that did not match at all) have now been added to the TMDB by yours truly :)

https://www.themoviedb.org/tv/100061-bad-obsession-motorsport-project-binky?language=en
https://www.themoviedb.org/tv/210690-shannons-club-tv

The updates and changes to Project Binky have been pulled down by Plex, but I am still waiting for Shannons Club TV to be added by Plex.

If you are wondering, yes, I did create the posters ;)

**Comment by ukdtom** [comment]
New build on G-Drive

**Comment by trumpy81** [comment]
New build installed, no issues as far as I can see :)

Minor update to Wiki Find Missing Episodes shortly.

Shannons Club TV was finally pulled down by Plex and it looks great too :)

I also added Shannons Legends of Motorsport to TMDB, waiting for that to be pulled down by Plex now. It is listed on the TVDB, but the listing there is locked, so I could make any adjustments, which sux.

**Comment by ukdtom** [comment]
Cool, and normally, it can take up to 48 hours before Plex server has the updated metadata

**Comment by trumpy81** [comment]
Yeah I figured it was something like that ... a real PITA ... lol

Shannons Legends of Motorsport just came down and it looks fantastic, includes all the specials too.

Just waiting for the latest updates to Project Binky to come down now :)
