### ISSUE TITLE
[BUG] Custom Levels > Custom fields won't sort

### ISSUE THREAD

**Issue by kiwichick888** [WebTools-NG/WebTools-NG#615]
**Describe the bug**
Currently using v1.1.2 and, I may be wrong, but in the previous version I'm sure I could drag the custom levels to any order. This version will let me do the dragging but after I click OK for the custom level save, the order changes back to whatever it was before.

**To Reproduce**
1. Go to 'Custom Levels'
2. Select a custom level (or create a new one).
3. In the 'custom fields' pane drag the items to a new order.
4. Click 'Save level', then 'OK'.
5. Order changes back to what it was previously.

**Expected behavior**
Expectation is order will not change back.

**Desktop:**
OS: [Windows 10 Pro

**Comment by ukdtom** [comment]
Working fine here....

Please switch file log level to Silly mode, restart WT-NG, and reproduce

After that, upload the log

**Comment by ukdtom** [comment]
@trumpy81 

I removed the attachment ;)

Do not post your json file without editing it first, since you are using a very special dev only option (Token)

**Comment by trumpy81** [comment]
Sorry about that, I did intend to edit it, but I was distracted by an issue with WinRAR and forgot ... doh!

Also see my updated post above.

**Comment by ukdtom** [comment]
`Note: This is only true if the Custom Level contains Export Art and/or Export Posters. Custom Levels that do not contain Export Art and/or Export Posters are NOT affected.`

Ahhh....Now I think I know what you mean here ;)

The fields named `Export Art` and `Export Posters` are not regular fields, are not even part of the export, and is always added in last by the code, when presented to the user

And differs from regular fields in the json file by been stored somewhere else

I have a custom level named `Test Sort` that also export Art and Posters, and is stored as follows:

![image](https://user-images.githubusercontent.com/4699449/196431598-3587158f-8771-409f-a15a-f1336474cf1f.png)

**Comment by trumpy81** [comment]
Yes, I think you got it by George! ... lol

Posters and Art are always sorted to the bottom of the list. I will go out on a limb and say that is by design ... at least as far as I can tell :)

**Comment by ukdtom** [comment]
`Update the Wiki?`

Good idea, and yes, indeed by design ;)

**Comment by trumpy81** [comment]
Wiki updated :)

**Comment by ukdtom** [comment]
Art and Posters are not, nor have they ever been part of the generated CSV file, but are instead exported as jpg files into a separate directory

Direct Wiki link: 
* https://github.com/WebTools-NG/WebTools-NG/wiki/CustomLevels
* https://github.com/WebTools-NG/WebTools-NG/wiki/Known-Issues#-exporttools
