### ISSUE TITLE
Fields missing from the Available Fields wiki page

### ISSUE THREAD

**Issue by kiwichick888** [WebTools-NG/WebTools-NG#616]
On the ExportTools - Available Fields page (https://github.com/WebTools-NG/WebTools-NG/wiki/Fields) none of the export art/posters are listed.

For example:
Export Show Art
Export Posters

**Comment by ukdtom** [comment]
As designed, since they are not regular fields, but merely triggers to kick off exporting of posters and art

**Comment by kiwichick888** [comment]
Thanks for clarifying that. It probably hasn't been noticed by other users but perhaps a note on that page explaining why they're not included would help anyone who does notice.

**Comment by ukdtom** [comment]
https://github.com/WebTools-NG/WebTools-NG/issues/615#issuecomment-1283648446

**Comment by kiwichick888** [comment]
Thank you.
