### ISSUE TITLE
[RFE] Home Page grammar error

### ISSUE THREAD

**Issue by trumpy81** [WebTools-NG/WebTools-NG#617]
Just a small issue with the grammar on the WebTools-NG Home page.

![Screenshot 2022-10-19 213919](https://user-images.githubusercontent.com/12381786/196680951-3aa9a071-e2c2-4b2f-a253-191ebe599d6d.png)

The highlighted line shown above, should read:
`Plex Media Server modules allow you to manage your server`
not
`Plex Media Server modules allows you to manage your server`

FYI, I updated some of the English translation strings at POEditor, so they may need to be reloaded :)

**Comment by ukdtom** [comment]
It's also on the translation site

Search for : `@:Modules.PMS.Name modules allows you to manage your server`

**Comment by ukdtom** [comment]
And hint...

You can find the translations on GitHub here, but please do not update it, only on POE
https://github.com/WebTools-NG/WebTools-NG/blob/master/public/locales/en.json

**Comment by trumpy81** [comment]
Thanks Tommy, I did search for those strings on POEditor, but it came up blank. Obviously I was searching for the wrong thing and I missed it when going through the list of strings ... lol

I thought about modifying the .json, but I remembered you told me not to once before, so I went to POEditor instead ... lol
