### ISSUE TITLE
[RFE] Wiki ExportTools

### ISSUE THREAD

**Issue by ukdtom** [WebTools-NG/WebTools-NG#618]
Could we add a recommendation to above with something like:

`We recommend you always export like 3-5 medias at level all, and then look at the output in order to create a custom level that gets what you want `

Also I think it's about time we add a completely new item to the help menu, named something like "Tutorial videos", and you know where to link ;)

**Comment by trumpy81** [comment]
How do I add a new item to the help menu in WT-NG?

Or do you mean on the Wiki?
