### ISSUE TITLE
[RFE] Allow to paste token into login screen

### ISSUE THREAD

**Issue by ukdtom** [WebTools-NG/WebTools-NG#619]
Instead of Usr/Pwd combo, we should also allow token login

**Comment by ukdtom** [comment]
@trumpy81  Note in above, we have a new option to logon

Will be part of the next release, when the time comes

**Comment by ukdtom** [comment]
Wiki update needed when released

**Comment by trumpy81** [comment]
I will wait for release and then update the Wiki as needed :)

**Comment by ukdtom** [comment]
> When using the old login from command line, what are the commands to login with 2FA enabled?

If using token at the command line, or with this new option, then Usr/Pwd/2FA combo isn't used

**Comment by trumpy81** [comment]
OK gotcha ... I wasn't sure for a while there ... lol

**Comment by trumpy81** [comment]
Just installed WT-NG v1.1.3.90b3d40 and tested Plex Token login. Working very well here :)

I have also turned on notifications for Google Drive. Hopefully, I will be notified when you update the files there now.

**Comment by ukdtom** [comment]
And see that the Wiki has been updated, so closing this, and Thanks
