### ISSUE TITLE
[RFE] ET Audio Display title shorten

### ISSUE THREAD

**Issue by ukdtom** [WebTools-NG/WebTools-NG#621]
Forum thread: https://forums.plex.tv/t/webtools-ng/598539/166?u=dane22

An Audio Display Title is like: "English (DTS-HD MA 7.1)"

Forum OP want's is shortened, in order to better see actual codec, but without  the language, so ask for a new field that produce:

"DTS-HD MA 7.1"

- [x] We need to add this to episodes
`- [ ] We need to add this to audio track`
- [x] We need to add this to movies
- [x] We Also need to add `Audio Stream Display Title` to movies
- [ ] We need to update the wiki

**Comment by ukdtom** [comment]
A Regex like `\((.*?)\)` should do it

**Comment by ukdtom** [comment]
Field name should be: `Audio Stream Codec (Human)`

**Comment by ukdtom** [comment]
Audio Track dropped for now, since output not consistent with the one from Movies and Episodes

**Comment by ukdtom** [comment]
Hi @trumpy81 

Could you add the field `Audio Stream Codec (Human)` as an avail field for Movies and Episodes?

**Comment by trumpy81** [comment]
Field added :)
