### ISSUE TITLE
[RFE] Export DVR specific tags

### ISSUE THREAD

**Issue by ukdtom** [WebTools-NG/WebTools-NG#622]
`<Media id="186009" duration="27720" bitrate="4956" width="1024" height="576" aspectRatio="1.78" audioChannels="2" audioCodec="mp2" videoCodec="h264" videoResolution="576" container="mpegts" videoFrameRate="PAL" beginOffset="1639" channelIdentifier="2" endOffset="130" mediaGrabBeginsAt="1667426400" mediaGrabDevice="device://tv.plex.grabbers.hdhomerun/14109029" mediaGrabPartialRecording="1" mediaGrabPartialRecordingReason="The recording was cancelled" mediaGrabStatus="complete" origin="dvr" videoProfile="main">
<Part accessible="1" exists="1" id="209394" key="/library/parts/209394/1667428070/file.ts" duration="27720" file="/share/CACHEDEV1_DATA/video/DVR/shows/Feldthaus & Bagger taber masken/Season 01/Feldthaus & Bagger taber masken - S01E02 - Episode 2.ts" size="17173424" container="mpegts" packetLength="188" videoProfile="main">
<Stream id="569711" streamType="1" codec="h264" index="0" bitrate="4700" bitDepth="8" chromaLocation="left" chromaSubsampling="4:2:0" codedHeight="576" codedWidth="1024" frameRate="25.000" hasScalingMatrix="0" height="576" level="31" profile="main" refFrames="4" scanType="progressive" streamIdentifier="256" width="1024" displayTitle="480p`

Like:

- [x] Media Channel Identifier 
- [x] Media Grab Begins At
- [x] Media Grab Device
- [x] Media Grab Partial Recording
- [x] Media Grab Partial Recording Reason
- [x] Media Grab Status
- [x] Media Origin
- [ ] Update Wiki
- [x] Done Movies
- [x] Done Episodes

**Comment by ukdtom** [comment]
Hi @trumpy81 

For fields avail, we need to add the following:

- [x] Media Channel Identifier 
- [x] Media Grab Begins At
- [x] Media Grab Device
- [x] Media Grab Partial Recording
- [x] Media Grab Partial Recording Reason
- [x] Media Grab Status
- [x] Media Origin

All above are valid for movies and episodes, and will show up for a media, that has been recorded with a DVR

When/if done, feel free to close this

**Comment by trumpy81** [comment]
Wiki has been updated. :)

**Comment by ukdtom** [comment]
And version has been released.
Huge thanks for all your work my friend

**Comment by trumpy81** [comment]
Thanks Tommy :)

I will check out the new version a little later and let you know if I find anything ... lol ... :^p
