### ISSUE TITLE
Media Info HDR types in Export?

### ISSUE THREAD

**Issue by millercentral** [WebTools-NG/WebTools-NG#625]
Hi, I was wondering if it is possible to make some of the additional fields shows in Plex "Media Info" available to the Media Export feature. A few examples of what I'm looking for:
```
D O V I B L Compat I D 1
D O V I B L Present true
D O V I Level 6
D O V I Present true
D O V I Profile 8
D O V I R P U Present true
D O V I Version 1.0
Display Title 4K DoVi/HDR10 (HEVC Main 10)
Extended Display Title 4K DoVi/HDR10 (HEVC Main 10)
```

- [x] DOVIBLCompatID (Video Stream DOVI BL compatible ID)
- [x] DOVIBLPresent (Video Stream DOVI BL Present)
- [x] DOVIELPresent (Video Stream DOVI EL Present)
- [x] DOVILevel (Video Stream DOVI Level)
- [x] DOVIPresent (Video Stream DOVI Present)
- [x] DOVIProfile (Video Stream DOVI Profile)
- [x] DOVIRPUPresent (Video Stream DOVI RPU Present)
- [x] DOVIVersion (Video Stream DOVI Version)
- [x] chromaLocation (Video Stream Chroma Location)

- [x] Add to Wiki

Thanks for considering!

**Comment by ukdtom** [comment]
Please upload a zip with an XML that show above

Ref: https://support.plex.tv/articles/201998867-investigate-media-information-and-formats/

**Comment by millercentral** [comment]
[media xml examples.zip](https://github.com/WebTools-NG/WebTools-NG/files/9973702/media.xml.examples.zip)
Two examples included in the attached zip. Thanks!

**Comment by ukdtom** [comment]
I sadly haven't got an HDR movie to test with :(

Could you create a small sample movie, like 100 Mb, upload it somewhere, and then DM me the download link on the Plex Forums?

Ref: https://support.plex.tv/articles/201035968-generating-sample-files-from-media/

**Comment by millercentral** [comment]
will do when I get home tonight, no problem.

**Comment by trumpy81** [comment]
Tommy, some Dolby Vision test videos are available here:
https://thedigitaltheater.com/2019/08/20/dolby-vision-trailers-h265-10bit-hdr-2160p-with-dolby-atmos/

**Comment by ukdtom** [comment]
Good call Andy, and I know, but there's so many, and to fetch all and import would take some time.
So if I simply could get the one needed, it would save me time, and time sadly isn't on my side right now :(

**Comment by trumpy81** [comment]
I hear you :)

Look for pufferfish on that download page. It should tick all the boxes for you. I have it in my collection and it does display the Dolby Vision extensions in Plex, but Plex does NOT identify the Dolby Atmos audio, so you probably wont be able to handle that.

Here's the link for that file:
https://we.tl/t-jSjEBnRzHU

Here is the XML for the pufferfish file:
[pufferfish.zip](https://github.com/WebTools-NG/WebTools-NG/files/9975485/pufferfish.zip)

**Comment by ukdtom** [comment]
Thanks @trumpy81 , but sadly didn't work :(
XML produced by above was:

```
<Part accessible="1" exists="1" id="271351" key="/library/parts/271351/1668034721/file.mp4" duration="63552" file="D:\video\Movies\The Lord of the Rings The Fellowship of the Ring (2001) {imdb-tt0120737}\The Lord of the Rings The Fellowship of the Ring (2001) {imdb-tt0120737} [Fake test HDR].mp4" size="40021822" container="mp4" has64bitOffsets="0" optimizedForStreaming="0" videoProfile="high">
<Stream id="540142" streamType="1" default="1" codec="h264" index="0" bitrate="4395" bitDepth="8" chromaLocation="left" chromaSubsampling="4:2:0" codedHeight="1088" codedWidth="1920" frameRate="24.000" hasScalingMatrix="0" height="1080" level="40" profile="high" refFrames="2" scanType="progressive" streamIdentifier="1" width="1920" displayTitle="1080p (H.264)" extendedDisplayTitle="1080p (H.264)"> </Stream>
<Stream id="540143" streamType="2" selected="1" default="1" codec="ac3" index="1" channels="6" bitrate="640" audioChannelLayout="5.1(side)" samplingRate="48000" streamIdentifier="2" displayTitle="Unknown (AC3 5.1)" extendedDisplayTitle="Unknown (AC3 5.1)"> </Stream>
</Part>
```

And as you might notice, no HDR info as OP requested

So I need a real sample, sorry

**Comment by ukdtom** [comment]
WOW, and now looking at your xml, that does contain the needed stuff...

Scratching head here, and I tested on my Windows PMS, that is way beyond any release...
Maybe Linux is needed for this...

I'll dig into it

**Comment by trumpy81** [comment]
I'm not sure what is happening here. I just checked the View XML in Plex again and now the Dolby Vision extensions are gone.

I only see the following now, no Dolby Vision extensions are shown at all:
![image](https://user-images.githubusercontent.com/12381786/200966028-f52bfd73-e2d4-4aee-9f68-d3883862d5ec.png)

Even MediaInfo (standalone program) is NOT showing the Dolby Vision extensions now. I am thinking this may be a Dolby/Windows licensing issue and maybe you will need to use Linux in order to see them.

**Comment by trumpy81** [comment]
I just checked using Ubuntu 22.04 and after installing Plex and setting up a test library, I do NOT see the Dolby extensions for the Amaze - Dolby Vision.mp4 file in Ubuntu either.

I'm not sure what is going on, but maybe it is Plex at fault, but why would MediaInfo (standalone) not show them either?

Very strange ....

**Comment by millercentral** [comment]
Here is a link to a onedrive folder with two sample files and the XML that Plex generates for each:
https://1drv.ms/u/s!AjJroKKvQCg2lLUQNvHioNmrgSpqRQ?e=8VAyHT

**Comment by trumpy81** [comment]
Thanks @millercentral

I downloaded your files and they do display the Dolby Vision extensions in Plex on Windows.

It seems the site I linked to is supplying non-DV files (even though they list them as DV) and I overwrote some of the files I had downloaded elsewhere, so that explains the disappearing extensions ... phew ... lol

I re-downloaded the files from this page: https://www.demolandia.net/4k-video-test/dolby-vision/page-1.html

And now I have the DV extensions again :)

**Comment by ukdtom** [comment]
Found missing `chromaLocation` as well ;)

**Comment by millercentral** [comment]
Just want to confirm these new fields are working for me and say thank you for adding them.

There are two other video fields related to this, that are low priority but which you might want to add before the final non-beta release: 
`Display Title: 4K HDR10 (HEVC Main 10)` and `Extended Display Title: `4K HDR10 (HEVC Main 10)`

In the MediaInfo XML these are located in Video > Media > Part > Stream.StreamType=1  (Which I think would map to "Video Stream DsiplayTitle/ExtendedDisplayTitle" fields in WebTool-NG) -- See the attached xml file for an example.
[HDR10 sample.xml.txt](https://github.com/WebTools-NG/WebTools-NG/files/10150391/HDR10.sample.xml.txt)

Thanks again!
