### ISSUE TITLE
[BUG] Comma Separated Values file is not separated by commas

### ISSUE THREAD

**Issue by Funtime60** [WebTools-NG/WebTools-NG#634]
By default, CSV files generated by this tool are separated by pipe characters rather than comma. I'm not sure how widespread RFC 4180 is but it clearly states the obvious, that a CSV must use commas. It can also be assumed the commas should ONLY be used for the delimiter and not anywhere else.

1. Fresh Install
2. Set Export Folder and Export as CSV flag
3. Export CSV
4. Open file in text editor

The file should use comma solely as the delimiter between fields and not anywhere else nor should they be replaced by any other character without an appropriate file name.

 - OS: Win 10 Pro x64

**Logs**
[WebTools-NG-Censored.zip](https://github.com/WebTools-NG/WebTools-NG/files/10095890/WebTools-NG-Censored.zip)
(I don't think you need my IP, since I was bored I censored everything you didn't need.)

**Comment by ukdtom** [comment]
This was done on purpose, due to the way internal code worked, where a comma in like the description field would cause problems.

When said, we have work in progress to refactor/re-code this, and is tracked in #580 so I'll close this

**Comment by trumpy81** [comment]
@Funtime60 
Just so that you are aware, you may choose the separator you wish to use in Global Settings > Export Settings.

See this page: https://github.com/WebTools-NG/WebTools-NG/wiki/ExportSettings for more details.
