### ISSUE TITLE
[BUG] Wiki has wrong entries

### ISSUE THREAD

**Issue by ukdtom** [WebTools-NG/WebTools-NG#641]
**Describe the bug**
After doing #625 I wanted to update the wiki page https://github.com/WebTools-NG/WebTools-NG/wiki/Fields

To my horror, I discovered that some fields are flipped between episodes and shows

The correct ones can be seen in the following files, when looking at the `all` section

* Shows: https://github.com/WebTools-NG/WebTools-NG/blob/master/src/components/modules/ExportTools/defs/def-Show.json
* Episodes: https://github.com/WebTools-NG/WebTools-NG/blob/master/src/components/modules/ExportTools/defs/def-Episode.json

@trumpy81 Would it be possible for you to run through them, and correct the Wiki page entries ?

**Comment by trumpy81** [comment]
It seems that the column headers were switched at some point. I have corrected that at least, but there is an issue with all fields that are marked with ?

We really need a positive answer one way or another on whether or not those fields are supported for the export type or not.

I have also made a change to the Available Fields page and the Available Fields for Playlists page. Check it out and let me know what you think.

Please don't ask me to change anything, they will be a nightmare to edit ... lol

I wish I could use a short variable to replace the images ... but you get that ... lol

**Comment by trumpy81** [comment]
Can you check the first 10 rows on the [Available Fields](https://github.com/WebTools-NG/WebTools-NG/wiki/Fields) page. There seems to be some errors there, but I am not sure if they are in fact errors or not.

**Comment by ukdtom** [comment]
Made you this, that I do hope works...

Those in doubt has been set to N/A

Open the CSV in Notepad++, and hopefully you can simply paste it in.
You will need to add repeated headers etc. though

[fields4.csv](https://github.com/WebTools-NG/WebTools-NG/files/10127743/fields4.csv)
[fields.ods](https://github.com/WebTools-NG/WebTools-NG/files/10127744/fields.ods)

**Comment by ukdtom** [comment]
And completely forgot...

I LOVE the icons you are using, that's simply so cool

**Comment by trumpy81** [comment]
Thanks Tommy :)

I have now updated those pages, hopefully with correct data ... lol

Give it a once over and let me know if you spot any errors etc.

**Comment by ukdtom** [comment]
Looks both cool and correct now...

And yes, a combo of csv and Notepad++ is always a hit :-D

Thanks for taking the time, as well as the nice icons, and will close this
