### ISSUE TITLE
[RFE] File Count on Download module page

### ISSUE THREAD

**Issue by trumpy81** [WebTools-NG/WebTools-NG#646]
In the Download module, after downloading a media list from a shared server, would it be possible to display a file count somewhere?

Just so we know how many files we have to browse through ... lol

**Comment by ukdtom** [comment]
Unsure what you mean here...

Could you provide a Mockup ?

**Comment by trumpy81** [comment]
This is just to give you an idea of what I am thinking of.

![Download-02](https://user-images.githubusercontent.com/12381786/205450669-10a6d874-898f-4004-aa4e-24f366856064.png)

**Comment by ukdtom** [comment]
Well, the word `files` would not be correct, since each entry could have both the media as well as several subs.

So could the word `files` be replaced with the word `medias` ?

**Comment by trumpy81** [comment]
No, but it could be replaced with Media ... lol ... :^p
