### ISSUE TITLE
[RFE] Download item selection

### ISSUE THREAD

**Issue by ukdtom** [WebTools-NG/WebTools-NG#647]
Currently, when selecting an item to download, we see the file name of the items

Instead, we should show it as:

| selected | Title                       | type    |
|    - [ ]     |  My Movie             | movie |
|    - [ ]     |  English                  | srt       |
|    - [ ]     |  English  (Forced)   | srt       |
|    - [ ]     |  Danish                  | ass       |

**Comment by ukdtom** [comment]
@trumpy81 

Maybe a pic update in the wiki?

**Comment by trumpy81** [comment]
Wiki updated.

**Comment by trumpy81** [comment]
Wiki updated.
