### ISSUE TITLE
[RFE] Module order is out of order

### ISSUE THREAD

**Issue by trumpy81** [WebTools-NG/WebTools-NG#650]
The fly out menu shows the module order as:

1. Download
2. ExportTools
3. Plex.TV
4. Plex Media Server

But the Welcome page shows the correct alphabetical order:

1. Download
2. ExportTools
3. Plex Media Server
4. Plex.TV

Could you correct the order of the modules on the fly out menu please :)

![WebTools-NG](https://user-images.githubusercontent.com/12381786/205480965-1767e55b-a138-4d93-a5f5-8dfbe61f8ffc.png)

**Comment by ukdtom** [comment]
@trumpy81 Order changed

Not sure, if it validates for new screen captures though, since minor

**Comment by trumpy81** [comment]
Already taken care of ... lol
