### ISSUE TITLE
[BUG] MacOS issues

### ISSUE THREAD

**Issue by trumpy81** [WebTools-NG/WebTools-NG#655]
**Describe the bug**
After installing and opening WebTools-NG and signing into Plex, you are presented with an error message (see below). 

1. Downloads, on one occasion it failed to add items to the queue. I tried repeatedly with mixed results, but seems to work now.
2. Edit a Custom Level, the Available fields list does not always display. The text appears and disappears making it hard to actually do anything.

**To Reproduce**
1. Open WebTools-NG and sign in, error message pops up.
1. Go to Download and add items to the queue
3. Click on show queue and observe no items.
4. Edit a Custom Level
5. Watch the text appear and disappear at random intervals. Moving the mouse around seems to effect the display of the text.

**Expected behavior**
Expect no error message, expect items to be added to queue, expect to be able to read Available fields list.

**Screenshots**
![Screenshot 2022-12-06 085540](https://user-images.githubusercontent.com/12381786/205764262-a04cd3f6-3a4d-487e-8c54-7b80c42b87c7.png)

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey, Big Sur and Mojave in Virtual Box VM's.

All of the above OS were tested, all showed the same issues with WebTools-NG v1.2.0 and v1.2.1 Beta.

**Additional context**
These issues may simply be the result of running Mac OS in a VM, but worth looking into if possible.

Maybe ask some owners of real Mac's in the Plex forums, if they see the same issues?

**Logs**
[WebTools-NG.zip](https://github.com/WebTools-NG/WebTools-NG/files/10158792/WebTools-NG.zip)

**Comment by ukdtom** [comment]
Got my dirty hands on an Airbook M2, and can sadly reproduce the login error :(
Also see it on Linux

**Comment by trumpy81** [comment]
Damn, I was hoping it was just a VM thing.

Do you see the other errors at all?

**Comment by ukdtom** [comment]
So far, I'm only looking at the login error, that happens on all platforms, if using User/Pwd

And found the reason as to why

**Comment by ukdtom** [comment]
Login issue fixed (Hopefully) on the newest public release

Will dig into the rest later, and please keep one issue pr. GHI ;)

**Comment by trumpy81** [comment]
I thought the real issue here was the VM, which is one issue, but it turned out more than that ... lol

Will test the new build later.

**Comment by trumpy81** [comment]
Tested new build in uBuntu and Monterey, login issue confirmed fixed.

Will post a GHI regarding the Available fields issue.
