### ISSUE TITLE
PMS Settings - Amount of Playlist and Playlists?

### ISSUE THREAD

**Issue by trumpy81** [WebTools-NG/WebTools-NG#665]
In PMS Settings, there are two listings:

1. Amount of playlist = I assume this is for the content of the playlists?
2. Amount of playlists = I assume this is for the actual playlists themselves?

Do I have them in the correct order?

I need to make a correction on the Wiki and Website, which is why I need to know ... lol

Currently I have both listed as the same thing :)

**Comment by ukdtom** [comment]
Both above are for how many items to fetch from the PMS in one go

`Amount of playlist` is for the contents for an individual playlist
`Amount of playlists` is when fetching the list of playlists for the server owner

**Comment by trumpy81** [comment]
Excellent, I will correct the website and wiki now, thanks! :)

**Comment by trumpy81** [comment]
All done!
