### ISSUE TITLE
[BUG] Find Media

### ISSUE THREAD

**Issue by ilmoro7766** [WebTools-NG/WebTools-NG#669]
**Describe the bug**
Plex Media Server --> Find MEdia does export a 1Kb file with just one line and two column filled.

**To Reproduce**
1. Go to 'Plex Media Server'
2. Click on 'Find Media'
3. Click on 'Select Media Library' and select a random library
4. The csv file content is:
Title|"PMS file"|"Filesystem"
N/A|N/A|Z:\Film\A-D\...e poi lo chiamarono Il Magnifico (1972).avi

Some libraries show more than on line however almost nothing compared to the number of item present in the db and in the file system.

Library Mapping page just shows green path on all libraries and all are correct.

**Expected behavior**
Exporting thounsands of records with details

**Desktop**
 - OS: Windows 10 latest version, fully updated

**Logs**
"Please provide WebTools-NG logs in a zip": cannot find the log file

**Comment by ukdtom** [comment]
Please set log level to debug, restart WebTools-NG and reproduce error, then upload a zip with logs
https://github.com/WebTools-NG/WebTools-NG/wiki/General-Settings

Logs:
https://github.com/WebTools-NG/WebTools-NG/wiki/File-Menu

**Comment by ilmoro7766** [comment]
Hi,

 

attached please find logs.

 

Thanks for support.

**Comment by trumpy81** [comment]
Please use the website to attach your logs, email does NOT work here.

You are aware that the Find Media module will only output files that are actually missing, either from your Plex database or from your filesystem?

Find Media does NOT list all files in a library, it only lists those that are missing.

**Comment by ilmoro7766** [comment]
Thanks a lot for the info, so the name is just confusing.

 

I need to have a file that includes details like filename and path and film name in Plex because I cannot find how Plex archived some of my video files…

**Comment by trumpy81** [comment]
Then you need to use the ExportTools module.

Create a Custom Level to output the details you wish to have output or use a built-in level.

For more details on creating a Custom Level see either of these pages:
Wiki: https://github.com/WebTools-NG/WebTools-NG/wiki/Custom-Levels
Website: https://webtools-ng.github.io/manual/custom-levels.html
