### ISSUE TITLE
Export to XSLX disabled? 

### ISSUE THREAD

**Issue by 6K6666** [WebTools-NG/WebTools-NG#683]
Curious why export to XSLX is disabled and if/when it will be added back. I heavily prefer the format that ExportTools uses when it exports to XSLX vs CSV. 

![raw](https://user-images.githubusercontent.com/68512888/230749816-ed95f4b8-f851-4704-926a-077996e7b522.png)

**Comment by trumpy81** [comment]
There were some issues with XLSX consuming excessive amounts of RAM.

It has been temporarily disabled until those issues can be resolved.

Unfortunately, I have no timeline for that to occur ATM.

**Comment by 6K6666** [comment]
> There were some issues with XLSX consuming excessive amounts of RAM.
> 
> It has been temporarily disabled until those issues can be resolved.
> 
> Unfortunately, I have no timeline for that to occur ATM, but rest assured it is on the Todo list.

Not a problem, thank you for replying so quickly
