### ISSUE TITLE
[BUG] Cannot export on fresh install of the program

### ISSUE THREAD

**Issue by MobyGamer** [WebTools-NG/WebTools-NG#686]
**Describe the bug**
Exports cannot be completed because the program asks the user "You need to select an output format in the ExportTools settings, like csv or xlsx" but no such option exists.

**To Reproduce**
1. Go to Global Settings, Export Settings
2. There is no way to pick the export format

I am a new user with a fresh install, so I have no legacy settings.  I'm guessing the developers removed xlsx support but forgot to force csv in the user interface and settings.  I would edit the JSON myself if I knew what to add...

**Desktop (please complete the following information):**
 - OS: Windows 11

**Logs**
The only relevant log entry is "[2023-05-12 17:53:48.370] [error] ET: No output format defined"

**Comment by MobyGamer** [comment]
Closing, as I did not immediately see the settings icon at the top right of the initial ExportTools window.  (A UI improvement request might be forthcoming.)

**Comment by trumpy81** [comment]
For future reference, see the Wiki for more information about using WebTools-NG.

https://github.com/WebTools-NG/WebTools-NG/wiki

For ExportTools Settings see: https://github.com/WebTools-NG/WebTools-NG/wiki/ExportTools-Settings
