### ISSUE TITLE
export fields pop-ups

### ISSUE THREAD

**Issue by jimlynnjulian** [WebTools-NG/WebTools-NG#688]
I can't find as definition for ExportTools field 'Media title.' I thought the filename was being referenced. 
This caused me to think that a context click or mouse-over pop-upp with a brief explanation would be good.
Maybe a pdf/txt document going into detail? I iunderstand most field names, but there are some that have me stymied.
I also thought the file path as well as name might be useful.
You might want to label the Rotten Tomatoes ratings as such, unless there might be some legal entanglements.

One more thing, Unicode. Some titles, e.g., Rashomon, Akira Kurosawa, Dir., have original titles in the original language. Is there some sort of notation that will allow external software to recognize the language?
I tried to import an exported csv file, into Open Office and theose foreign characters are gibberish.

Thanks for the app.
Jim J.

**Comment by trumpy81** [comment]
First of all, I believe the Media title field has been deprecated by Plex and is no longer used.

However, if you should find a file that populates that field, you should probably re-match and Refresh Metadata for that file.

I would recommend you try using Libre Office Calc (part of the Libre Office suite and counters MS Excel) to open the .csv files.
Libre Office Calc does not have any issues handling Unicode characters as demonstrated below:

![image](https://github.com/WebTools-NG/WebTools-NG/assets/12381786/a04821ae-f800-4f16-8e43-1fd8da66f32f)

The file Line Number followed by the Title and Original Title fields from a Movies library output are shown above.

**Comment by jimlynnjulian** [comment]
I've already seen the link enclosed. That's what inspired the pop-up/context suggestion.
I tried Libre Office  long time ago. Don't remember the reason, but I didn't care for it.  I'm going to examine Open Office import options for potential solutions.
Thanks.

**Comment by trumpy81** [comment]
Thanks, I did consider what you suggested re: pop up definitions, many moons ago, but the Markdown language as implemented by Github is very limited and does not allow for pop up messages, I certainly could not get it to work.

I could implement pop ups on the website, but that means a lot of additional work and I am too lazy for that ... lol

If you need to determine the function/meaning of a field, include that field in an ExportTools output using Custom Levels along with at least the Title & Part File fields.

When outputting the Custom Level, limit the number of items to 5 or 10 items only. 

That will allow you to see what data is actually output by the field in question and should give you some understanding of what that field represents.
