### ISSUE TITLE
Find Media Listing All Media[BUG]

### ISSUE THREAD

**Issue by OnceNowFuture** [WebTools-NG/WebTools-NG#689]
**Describe the bug**
Find Media seems to export all media, not just missing items. 

**To Reproduce**
1. Go to 'Find Media'
2. Click on 'Select Media Library' e.g. Films
3. Click Run
4. Exports .csv successfully 
5. .csv then exports all films currently on Plex/Local Drives

**Expected behavior**
Should only show missing files. 

**Screenshots**
![image](https://github.com/WebTools-NG/WebTools-NG/assets/130673324/75718043-e03f-4cfd-96da-fd3996c0c521)
![image](https://github.com/WebTools-NG/WebTools-NG/assets/130673324/ed2b9957-643f-4b83-88cb-d856690d6ab7)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
Apologies if I'm missing something really simple here! I've tried looking at the export settings and can't see anything that would make this happen, and I'm quite confused.

**Comment by ukdtom** [comment]
Switch log level to debug level, restart and reproduce.
Then upload the log

**Comment by trumpy81** [comment]
I am not seeing that behaviour here at all. Following your steps, I have a single .csv file that is empty. except for the column headers (I have no missing files).

WebTools-NG v1.2.1.f962812
Windows 11 Pro

Ran the test again after removing a file from my local disk and WebTools-NG correctly identified the missing file. There was no second .csv file output at all.

![image](https://github.com/WebTools-NG/WebTools-NG/assets/12381786/fde1bb5f-3a8b-488a-87b4-360ba59201c9)


I am NOT sure why WebTools-NG would output a second .csv file, did you correctly select `Find Media` in the WebTools-NG menu (left of screen) and NOT ExportTools?

![image](https://github.com/WebTools-NG/WebTools-NG/assets/12381786/0015f239-3fe9-482a-be16-02ecc266eab4)

ExportTools has the `Find Missing Episodes` feature, but that can only be used with TV Shows.

More details here: https://github.com/WebTools-NG/WebTools-NG/wiki/Find-Missing-Episodes
`Find Media` is detailed here: https://github.com/WebTools-NG/WebTools-NG/wiki/Find-Media

**Comment by ukdtom** [comment]
I suspect either a bad naming structure with the `1` directory, or a bad mapping been set

Logs will show

**Comment by OnceNowFuture** [comment]
Thank you both for your responses! 

I'm fairly confident it will be something to do with my naming structure, definitely not the program at all. 

@trumpy81 Yeah, I used the 'Find Media' option. I did scour the wiki as well, as I was certain I must be missing something (still might be, of course!) Weirdly, for a different library (documentaries, which I've added a lot more recently), it worked perfectly. 

I have also taken off one of my libraries and re-added it to Plex, on the off chance it would re-map it to where it should be (I've had to clone the Windows install 6 months back, inc. Plex install files & reg key), in case that had caused anything weird, but it came up with the same result. 

Anyway, really appreciate you having a look at this, I've attached the logs.
[WebTools-NG.zip](https://github.com/WebTools-NG/WebTools-NG/files/11858072/WebTools-NG.zip)

Thanks!

**Comment by trumpy81** [comment]
Looking at your log file, you seem to have media placed in the root of the drive. This is NOT advised at all.

I would suggest you create a folder such as `Movies` and then place all relevant media (files/folders) inside that folder.

I also noticed that you seem to have the wrong drive/folder configured in Library Mapping, although I could be wrong about that.

As far as I can tell, Plex thinks the files reside on F:\ while WebTools-NG appears to be configured for I:\ drive.

This would cause WebTools to output the entire library as missing, which may explain what you are seeing?

**Comment by OnceNowFuture** [comment]
Oh really? I had no idea! I basically have a few different hard drives, some just for films and some just for TV - hence why I've done it that way. 

I'll move everything off the root of the drives, and try again. The documentaries I mentioned were in a subfolder, so this matches up with what you said. 

As for the library mapping - that should be done correctly, it's just where I have multiple library locations - see screenshot:
![image](https://github.com/WebTools-NG/WebTools-NG/assets/130673324/a8b5fc25-350e-46ff-b8c6-c07f75626569)
Also, as I don't believe that any I:\Films files showed up, I think you've solved it!

I'm just waiting for Plex to finish rescanning everything, will test again and then mark as solved.

Thank you again so much for your help!

**Comment by trumpy81** [comment]
Yeah it can be a pain trying to keep track of things when you have multiple drives involved.

I hope you get things sorted out OK.

I also highly recommend you use FileBot to automatically rename your files/folders to Plex's liking. It can save you mountains of work ... lol

It is no longer free, but for only $6 USD for a year, it is well worth it in my opinion. You can also get a lifetime license at reasonable cost too.

https://www.filebot.net

**Comment by OnceNowFuture** [comment]
Yup, just ran another scan and that's completely fixed it, thanks again!! 

Oh that looks really good - thanks for the reccomendation. I've been using Rename My TV Series, but it's a little clunky and this looks great - thanks for the tip buddy!

**Comment by trumpy81** [comment]
I have tried several other naming programs, but I always come back to FileBot. It is easy to configure and you can have qBittorent (and others) configured to automatically invoke FileBot when saving downloaded files too.

If you use FileBot manually, configure the naming format as `{plex}` to automatically name things for Plex. It's too easy :)

**Comment by OnceNowFuture** [comment]
This is such great advice, thank you! To my shame, I actually use a different PC for qBittorrent as I was unsure how to run both Plex/Steam while also using a VPN - but I've just read about split tunnelling, so that might make my life a whole lot easier :)
