### ISSUE TITLE
[BUG] Can't copy view state copy: loading forever

### ISSUE THREAD

**Issue by kevinvalle22** [WebTools-NG/WebTools-NG#692]
**Describe the bug**
When I try to copy view state from one user to another it keeps loading.

**To Reproduce**
1. Click on the server you wanna access ( I only own one)
2. Go to 'view state copy section'
3. Read the status message: Collecting user info . . . Please wait
4. Keep waiting

**Expected behavior**
It should give me the list with the users from my server as stated in https://github.com/WebTools-NG/WebTools-NG/wiki/View-State-Copy

**Screenshots**
![image](https://github.com/WebTools-NG/WebTools-NG/assets/26128231/0ccfe460-8b8b-4877-bf9a-646bbb17961c)
![image](https://github.com/WebTools-NG/WebTools-NG/assets/26128231/2c7c2365-7924-400d-b3ad-fa85fe095045)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 22H2 22621.1992

**Additional context**
I changed the logs to verbose
I restarted the application several times, same result
I relogged to the app several times, same result
I executed the application as admin, same result

**Logs**

Moderator: Log deleted

**Comment by trumpy81** [comment]
From your logs, it appears that you are unable to communicate with Plex, I see a 401 error and a 1031 error.
401 = Not Authorised, 1031 = Incorrect server configuration.

It also appears that a non standard address is being used to communicate with Plex or at least it is not one I recognise.

Make sure you are not connecting via a VPN or the like and make sure you are properly signed into your server and it is claimed etc.

Also check that WebTools-NG or your Plex server are not being blocked by a Firewall (Anti-Virus) or the like.

If the above does not help, try rebooting your PC and/or your local network.

**Comment by kevinvalle22** [comment]
![image](https://github.com/WebTools-NG/WebTools-NG/assets/26128231/eae21899-9b2e-407b-b7a1-da5a7852ea63)
I am able to see user list on Plext.tv section
I logged in using the plex token
I am not accessing plex through a VPN it's a local default connection http://127.0.0.1:32400/ I'm running Webtools ON THE LOCAL COMPUTER 
I rebooted the pc 
No firewall issues for plex or Webtools-NG
btw I cannot access plex outside of my local network due to my internet service provider doesn't allow me to have a dedicated ip (CG NAT) so I use zerotierone when I am outside, idk if that has something to do with it

**Comment by trumpy81** [comment]
zerotierone may well have something to do with your issue.

I suspect that since you don't have a direct connection to plex.tv, then Plex may be rejecting the connection for one reason or another, hence the 401, 1031 errors.

I did a trace route on the address shown in your logs and it keeps resolving to a location in Belarus.

Does that sound correct to you?

If it does not, then I would recommend you scan the PC for malware/spyware, if only as a precautionary measure.

The only other thing I can suggest, is that you check your setup/configuration for zerotierone.

View State Copy will only return your user, unless you have Plex Home configured and allow local users (family) to access the server via Plex Home on your local LAN network.

It will NOT allow users who share your server from remote locations.

**Comment by kevinvalle22** [comment]
How can I do trace route? And what address are you talking about? Could you provide more info on that please?

**Comment by trumpy81** [comment]
To do a trace route, go here: http://cqcounter.com/whois/ click on the trace route tab and type in the address you wish to trace.

The address can be found at line 403 in your log, near the end of the file.

**Comment by kevinvalle22** [comment]
Oh that's fine I thought you were talking about another ip I didn't know, phew that scared me for a second. That actually is Ngrok but thanks for letting me know!
https://github.com/inconshreveable/ngrok

I'll check my zerotier config later and I'll update, btw can I delete the log file or the content on it so it's more readable?. I cleaned the addresses I don't use anymore

**Comment by trumpy81** [comment]
Sure, you can delete the log, I'm done with it now ... lol

No doubt ngrok have a location in Bulgaria ... lol

**Comment by kevinvalle22** [comment]
[WebTools-NG.zip](https://github.com/WebTools-NG/WebTools-NG/files/12391762/WebTools-NG.zip)
New logs, some help would be very much appreciated.

**Comment by trumpy81** [comment]
Unfortunately, the new logs do not help at all. There is very little content in the new logs and no indication of any errors.

```
[2023-08-20 16:41:58.743] [warn]  [plextv.js] (checkServerConnect) No response recieved
[2023-08-20 16:41:58.743] [info]  [plextv.js] (checkServerConnect)Returning valid address as: https://192.168.18.9:32400
[2023-08-20 16:41:58.744] [info]  ViewState selected server changed
```
From the log snippets above, WebTools-NG appears to be receiving a slow response from your Plex server. The response is satisfied on the next line of the log though and as far as I can tell, everything is working as it is supposed to, so I am not sure why WebTools-NG is not displaying any results for you.

As you can see in the image below, I do not have any issues displaying my user. I only have one user on my Plex server as I have not setup Plex home at all (I do not need it).

![image](https://github.com/WebTools-NG/WebTools-NG/assets/12381786/fc15ecaa-6058-4deb-84d0-7ea62c9b1edb)

I would still consider your connection method to be an issue, although that does seem unlikely, given that all responses to/from plex.tv and your server seem to be functioning correctly.

You could try rebooting your modem/router and everything connected to it.

Have you uninstalled/reinstalled WebTools-NG? 

Do you have another PC/Laptop that you can test with or could you possibly borrow one to test with?

You could also use a VM to test with if you are familiar with using Virtual Machines at all?

You would probably need to install WebTools-NG and Plex on the test machine and setup a single library with a few files in it for testing. No need to setup Plex home on it, as you simply want to see WebTools-NG display a user and not loop endlessly.

Set up Plex as a second server, do NOT use your existing username/password. You can uninstall WebTools-NG and Plex when you are done testing.

If it works, that would at least rule out WebTools-NG as a possibly cause and point to your current PC and/or a connection issue to the current PC.

If you get the same results as your current PC, then that may possibly indicate a connection issue on the current PC.

**Comment by ukdtom** [comment]
It's a bug in PMS, that has been reported back to Plex

See: https://forums.plex.tv/t/webtools-ng/598539/209

**Comment by ukdtom** [comment]
https://forums.plex.tv/t/plex-media-server/30447/596

**Comment by kevinvalle22** [comment]
Thanks! I'll wait for the public release
