### ISSUE TITLE
Where to get Bundle file

### ISSUE THREAD

**Issue by amj87** [WebTools-NG/WebTools-NG#704]
Hi,
How can I get the BUNDLE to install on my QNAP?

I usually copy BUNDLE file into my PLUGIN folder and it will appear on PMS.

Thanks,

**Comment by trumpy81** [comment]
You are referring to the WebTools Plugin which is no longer supported by Plex. 

I suggest you download WebTools-NG and use that instead.

Full details may be found here: https://github.com/WebTools-NG/WebTools-NG/wiki

**Comment by amj87** [comment]
> You are referring to the WebTools Plugin which is no longer maintained.
> 
> I suggest you download WebTools-NG and use that instead.
> 
> Full details may be found here: https://github.com/WebTools-NG/WebTools-NG/wiki

Hi,
I went through the below link, I couldn't figure out how to install on my QNAP server.

https://github.com/WebTools-NG/WebTools-NG/wiki/Installing-WebTools-NG

There is only instruction for Windows/Mac/Linux.

Thanks,

**Comment by trumpy81** [comment]
Then I suggest you start reading the pages I linked to.

WebTools-NG does NOT get installed on any NAS! You install it on your PC or laptop. It then communicates with your Plex server/s via the internet and Plex.tv.

**Comment by amj87** [comment]
That's clear, only this I need a 24/7 working PC.

Thanks,

**Comment by trumpy81** [comment]
What has that got to do with anything?

You don't run WebTools-NG 24/7 ... you only use it when you need it,

**Comment by amj87** [comment]
I was referring to unsupported apps, like TRAKT.

Is it available in NG?

Regards,

**Comment by trumpy81** [comment]
No plugins are available in WebTools-NG because they are not supported by Plex and have not been supported for over 5 years now.

**Comment by amj87** [comment]
thanks, for the clarity.
