### ISSUE TITLE
Download doesn't show all library types

### ISSUE THREAD

**Issue by kiwichick888** [WebTools-NG/WebTools-NG#708]
Am I misunderstanding how Download works? I see only Movies and Other Videos library types. Does it not work for TV Shows and Music? I am the server owner and have a Plex Pass.

Music also doesn't appear in Find Media or Library Mapping.

**Comment by ukdtom** [comment]
Only movie libraries are currently supported

**Comment by kiwichick888** [comment]
Then why isn't that stated in the app or the wiki? And do you specifically mean Movie libraries as in the type when the library is created? Because, as I stated, Other Video libraries are included.

You also didn't reply to my comment about Music for Find Media and Library Mapping. This is obviously nothing to do with only Movies libraries supported because TV appears in both of them.
